// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/ratelimit/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CheckExternal provides a mock function with given fields: ctx, targetKey, bucketKey
func (_m *MockService) CheckExternal(ctx context.Context, targetKey string, bucketKey string) (model.CheckResponse, error) {
	ret := _m.Called(ctx, targetKey, bucketKey)

	if len(ret) == 0 {
		panic("no return value specified for CheckExternal")
	}

	var r0 model.CheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.CheckResponse, error)); ok {
		return rf(ctx, targetKey, bucketKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.CheckResponse); ok {
		r0 = rf(ctx, targetKey, bucketKey)
	} else {
		r0 = ret.Get(0).(model.CheckResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, targetKey, bucketKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CheckExternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckExternal'
type MockService_CheckExternal_Call struct {
	*mock.Call
}

// CheckExternal is a helper method to define mock.On call
//   - ctx context.Context
//   - targetKey string
//   - bucketKey string
func (_e *MockService_Expecter) CheckExternal(ctx interface{}, targetKey interface{}, bucketKey interface{}) *MockService_CheckExternal_Call {
	return &MockService_CheckExternal_Call{Call: _e.mock.On("CheckExternal", ctx, targetKey, bucketKey)}
}

func (_c *MockService_CheckExternal_Call) Run(run func(ctx context.Context, targetKey string, bucketKey string)) *MockService_CheckExternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_CheckExternal_Call) Return(_a0 model.CheckResponse, _a1 error) *MockService_CheckExternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CheckExternal_Call) RunAndReturn(run func(context.Context, string, string) (model.CheckResponse, error)) *MockService_CheckExternal_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExternalTarget provides a mock function with given fields: ctx, t, createdBy
func (_m *MockService) CreateExternalTarget(ctx context.Context, t model.Target, createdBy string) (model.Target, error) {
	ret := _m.Called(ctx, t, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateExternalTarget")
	}

	var r0 model.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Target, string) (model.Target, error)); ok {
		return rf(ctx, t, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Target, string) model.Target); ok {
		r0 = rf(ctx, t, createdBy)
	} else {
		r0 = ret.Get(0).(model.Target)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Target, string) error); ok {
		r1 = rf(ctx, t, createdBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateExternalTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExternalTarget'
type MockService_CreateExternalTarget_Call struct {
	*mock.Call
}

// CreateExternalTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - t model.Target
//   - createdBy string
func (_e *MockService_Expecter) CreateExternalTarget(ctx interface{}, t interface{}, createdBy interface{}) *MockService_CreateExternalTarget_Call {
	return &MockService_CreateExternalTarget_Call{Call: _e.mock.On("CreateExternalTarget", ctx, t, createdBy)}
}

func (_c *MockService_CreateExternalTarget_Call) Run(run func(ctx context.Context, t model.Target, createdBy string)) *MockService_CreateExternalTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Target), args[2].(string))
	})
	return _c
}

func (_c *MockService_CreateExternalTarget_Call) Return(_a0 model.Target, _a1 error) *MockService_CreateExternalTarget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateExternalTarget_Call) RunAndReturn(run func(context.Context, model.Target, string) (model.Target, error)) *MockService_CreateExternalTarget_Call {
	_c.Call.Return(run)
	return _c
}

// CreateToken provides a mock function with given fields: ctx, app, name, scopePrefix, createdBy
func (_m *MockService) CreateToken(ctx context.Context, app string, name string, scopePrefix string, createdBy string) (model.AppToken, string, error) {
	ret := _m.Called(ctx, app, name, scopePrefix, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 model.AppToken
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (model.AppToken, string, error)); ok {
		return rf(ctx, app, name, scopePrefix, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) model.AppToken); ok {
		r0 = rf(ctx, app, name, scopePrefix, createdBy)
	} else {
		r0 = ret.Get(0).(model.AppToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) string); ok {
		r1 = rf(ctx, app, name, scopePrefix, createdBy)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string) error); ok {
		r2 = rf(ctx, app, name, scopePrefix, createdBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockService_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - app string
//   - name string
//   - scopePrefix string
//   - createdBy string
func (_e *MockService_Expecter) CreateToken(ctx interface{}, app interface{}, name interface{}, scopePrefix interface{}, createdBy interface{}) *MockService_CreateToken_Call {
	return &MockService_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, app, name, scopePrefix, createdBy)}
}

func (_c *MockService_CreateToken_Call) Run(run func(ctx context.Context, app string, name string, scopePrefix string, createdBy string)) *MockService_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockService_CreateToken_Call) Return(_a0 model.AppToken, _a1 string, _a2 error) *MockService_CreateToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_CreateToken_Call) RunAndReturn(run func(context.Context, string, string, string, string) (model.AppToken, string, error)) *MockService_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExternalTarget provides a mock function with given fields: ctx, key
func (_m *MockService) DeleteExternalTarget(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExternalTarget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteExternalTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExternalTarget'
type MockService_DeleteExternalTarget_Call struct {
	*mock.Call
}

// DeleteExternalTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockService_Expecter) DeleteExternalTarget(ctx interface{}, key interface{}) *MockService_DeleteExternalTarget_Call {
	return &MockService_DeleteExternalTarget_Call{Call: _e.mock.On("DeleteExternalTarget", ctx, key)}
}

func (_c *MockService_DeleteExternalTarget_Call) Run(run func(ctx context.Context, key string)) *MockService_DeleteExternalTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteExternalTarget_Call) Return(_a0 error) *MockService_DeleteExternalTarget_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteExternalTarget_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteExternalTarget_Call {
	_c.Call.Return(run)
	return _c
}

// EffectiveRule provides a mock function with given fields: key
func (_m *MockService) EffectiveRule(key string) (model.EffectiveRule, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for EffectiveRule")
	}

	var r0 model.EffectiveRule
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (model.EffectiveRule, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) model.EffectiveRule); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(model.EffectiveRule)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockService_EffectiveRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EffectiveRule'
type MockService_EffectiveRule_Call struct {
	*mock.Call
}

// EffectiveRule is a helper method to define mock.On call
//   - key string
func (_e *MockService_Expecter) EffectiveRule(key interface{}) *MockService_EffectiveRule_Call {
	return &MockService_EffectiveRule_Call{Call: _e.mock.On("EffectiveRule", key)}
}

func (_c *MockService_EffectiveRule_Call) Run(run func(key string)) *MockService_EffectiveRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_EffectiveRule_Call) Return(_a0 model.EffectiveRule, _a1 bool) *MockService_EffectiveRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_EffectiveRule_Call) RunAndReturn(run func(string) (model.EffectiveRule, bool)) *MockService_EffectiveRule_Call {
	_c.Call.Return(run)
	return _c
}

// ListTargets provides a mock function with given fields: ctx
func (_m *MockService) ListTargets(ctx context.Context) ([]model.Target, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTargets")
	}

	var r0 []model.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Target, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Target); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTargets'
type MockService_ListTargets_Call struct {
	*mock.Call
}

// ListTargets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListTargets(ctx interface{}) *MockService_ListTargets_Call {
	return &MockService_ListTargets_Call{Call: _e.mock.On("ListTargets", ctx)}
}

func (_c *MockService_ListTargets_Call) Run(run func(ctx context.Context)) *MockService_ListTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListTargets_Call) Return(_a0 []model.Target, _a1 error) *MockService_ListTargets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListTargets_Call) RunAndReturn(run func(context.Context) ([]model.Target, error)) *MockService_ListTargets_Call {
	_c.Call.Return(run)
	return _c
}

// ListTokens provides a mock function with given fields: ctx
func (_m *MockService) ListTokens(ctx context.Context) ([]model.AppToken, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTokens")
	}

	var r0 []model.AppToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.AppToken, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.AppToken); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AppToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTokens'
type MockService_ListTokens_Call struct {
	*mock.Call
}

// ListTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListTokens(ctx interface{}) *MockService_ListTokens_Call {
	return &MockService_ListTokens_Call{Call: _e.mock.On("ListTokens", ctx)}
}

func (_c *MockService_ListTokens_Call) Run(run func(ctx context.Context)) *MockService_ListTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListTokens_Call) Return(_a0 []model.AppToken, _a1 error) *MockService_ListTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListTokens_Call) RunAndReturn(run func(context.Context) ([]model.AppToken, error)) *MockService_ListTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ResetCounters provides a mock function with given fields: ctx, key
func (_m *MockService) ResetCounters(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ResetCounters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ResetCounters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetCounters'
type MockService_ResetCounters_Call struct {
	*mock.Call
}

// ResetCounters is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockService_Expecter) ResetCounters(ctx interface{}, key interface{}) *MockService_ResetCounters_Call {
	return &MockService_ResetCounters_Call{Call: _e.mock.On("ResetCounters", ctx, key)}
}

func (_c *MockService_ResetCounters_Call) Run(run func(ctx context.Context, key string)) *MockService_ResetCounters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ResetCounters_Call) Return(_a0 error) *MockService_ResetCounters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ResetCounters_Call) RunAndReturn(run func(context.Context, string) error) *MockService_ResetCounters_Call {
	_c.Call.Return(run)
	return _c
}

// ResetDefaults provides a mock function with given fields: ctx, key
func (_m *MockService) ResetDefaults(ctx context.Context, key string) (model.Target, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ResetDefaults")
	}

	var r0 model.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Target, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Target); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(model.Target)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ResetDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetDefaults'
type MockService_ResetDefaults_Call struct {
	*mock.Call
}

// ResetDefaults is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockService_Expecter) ResetDefaults(ctx interface{}, key interface{}) *MockService_ResetDefaults_Call {
	return &MockService_ResetDefaults_Call{Call: _e.mock.On("ResetDefaults", ctx, key)}
}

func (_c *MockService_ResetDefaults_Call) Run(run func(ctx context.Context, key string)) *MockService_ResetDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ResetDefaults_Call) Return(_a0 model.Target, _a1 error) *MockService_ResetDefaults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ResetDefaults_Call) RunAndReturn(run func(context.Context, string) (model.Target, error)) *MockService_ResetDefaults_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function with given fields: ctx, id
func (_m *MockService) RevokeToken(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockService_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) RevokeToken(ctx interface{}, id interface{}) *MockService_RevokeToken_Call {
	return &MockService_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, id)}
}

func (_c *MockService_RevokeToken_Call) Run(run func(ctx context.Context, id string)) *MockService_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_RevokeToken_Call) Return(_a0 error) *MockService_RevokeToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_RevokeToken_Call) RunAndReturn(run func(context.Context, string) error) *MockService_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTarget provides a mock function with given fields: ctx, key, patch, updatedBy
func (_m *MockService) UpdateTarget(ctx context.Context, key string, patch model.TargetPatch, updatedBy string) (model.Target, error) {
	ret := _m.Called(ctx, key, patch, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTarget")
	}

	var r0 model.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.TargetPatch, string) (model.Target, error)); ok {
		return rf(ctx, key, patch, updatedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.TargetPatch, string) model.Target); ok {
		r0 = rf(ctx, key, patch, updatedBy)
	} else {
		r0 = ret.Get(0).(model.Target)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.TargetPatch, string) error); ok {
		r1 = rf(ctx, key, patch, updatedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTarget'
type MockService_UpdateTarget_Call struct {
	*mock.Call
}

// UpdateTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - patch model.TargetPatch
//   - updatedBy string
func (_e *MockService_Expecter) UpdateTarget(ctx interface{}, key interface{}, patch interface{}, updatedBy interface{}) *MockService_UpdateTarget_Call {
	return &MockService_UpdateTarget_Call{Call: _e.mock.On("UpdateTarget", ctx, key, patch, updatedBy)}
}

func (_c *MockService_UpdateTarget_Call) Run(run func(ctx context.Context, key string, patch model.TargetPatch, updatedBy string)) *MockService_UpdateTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.TargetPatch), args[3].(string))
	})
	return _c
}

func (_c *MockService_UpdateTarget_Call) Return(_a0 model.Target, _a1 error) *MockService_UpdateTarget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateTarget_Call) RunAndReturn(run func(context.Context, string, model.TargetPatch, string) (model.Target, error)) *MockService_UpdateTarget_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
