apiVersion: v1
kind: Service
metadata:
  name: all-in-one
  labels:
    app: all-in-one
spec:
  type: LoadBalancer
  # loadBalancerIP: 192.168.68.91  # Uncomment and set your MetalLB IP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: all-in-one
