with-expecter: true
packages:
  github.com/all-in-one/internal/query:
    interfaces:
      QueryOptions:
        config:
          dir: "internal/listing/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
  github.com/all-in-one/internal/authnz/repository:
    interfaces:
      UserRepository:
        config:
          dir: "internal/authnz/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      SessionRepository:
        config:
          dir: "internal/authnz/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      Storage:
        config:
          dir: "internal/authnz/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      TOTPRepository:
        config:
          dir: "internal/authnz/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
  github.com/all-in-one/internal/listing/repository:
    interfaces:
      ItemRepository:
        config:
          dir: "internal/listing/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      TopicRepository:
        config:
          dir: "internal/listing/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      Storage:
        config:
          dir: "internal/listing/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
  github.com/all-in-one/internal/shortener/repository:
    interfaces:
      ShortLinkRepository:
        config:
          dir: "internal/shortener/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
  github.com/all-in-one/internal/rbac/repository:
    interfaces:
      FeatureRepository:
        config:
          dir: "internal/rbac/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      GroupRepository:
        config:
          dir: "internal/rbac/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      GroupFeatureRepository:
        config:
          dir: "internal/rbac/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      OverrideRepository:
        config:
          dir: "internal/rbac/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      UserGroupRepository:
        config:
          dir: "internal/rbac/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      Storage:
        config:
          dir: "internal/rbac/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
  github.com/all-in-one/internal/rbac/handler:
    interfaces:
      Service:
        config:
          dir: "internal/rbac/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
  github.com/all-in-one/internal/authnz/handler:
    interfaces:
      AccessResolver:
        config:
          dir: "internal/authnz/handler/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
  github.com/all-in-one/internal/ratelimit/repository:
    interfaces:
      RuleRepository:
        config:
          dir: "internal/ratelimit/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      CounterRepository:
        config:
          dir: "internal/ratelimit/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
      Storage:
        config:
          dir: "internal/ratelimit/service/mocks"
          filename: "mock_{{.InterfaceName}}.go"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: mocks
