// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	repository "github.com/all-in-one/internal/oidc/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// ClientRepo provides a mock function with no fields
func (_m *MockStorage) ClientRepo() repository.ClientRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientRepo")
	}

	var r0 repository.ClientRepository
	if rf, ok := ret.Get(0).(func() repository.ClientRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ClientRepository)
		}
	}

	return r0
}

// MockStorage_ClientRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientRepo'
type MockStorage_ClientRepo_Call struct {
	*mock.Call
}

// ClientRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) ClientRepo() *MockStorage_ClientRepo_Call {
	return &MockStorage_ClientRepo_Call{Call: _e.mock.On("ClientRepo")}
}

func (_c *MockStorage_ClientRepo_Call) Run(run func()) *MockStorage_ClientRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_ClientRepo_Call) Return(_a0 repository.ClientRepository) *MockStorage_ClientRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_ClientRepo_Call) RunAndReturn(run func() repository.ClientRepository) *MockStorage_ClientRepo_Call {
	_c.Call.Return(run)
	return _c
}

// KeyRepo provides a mock function with no fields
func (_m *MockStorage) KeyRepo() repository.KeyRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for KeyRepo")
	}

	var r0 repository.KeyRepository
	if rf, ok := ret.Get(0).(func() repository.KeyRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.KeyRepository)
		}
	}

	return r0
}

// MockStorage_KeyRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyRepo'
type MockStorage_KeyRepo_Call struct {
	*mock.Call
}

// KeyRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) KeyRepo() *MockStorage_KeyRepo_Call {
	return &MockStorage_KeyRepo_Call{Call: _e.mock.On("KeyRepo")}
}

func (_c *MockStorage_KeyRepo_Call) Run(run func()) *MockStorage_KeyRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_KeyRepo_Call) Return(_a0 repository.KeyRepository) *MockStorage_KeyRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_KeyRepo_Call) RunAndReturn(run func() repository.KeyRepository) *MockStorage_KeyRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
