// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/oidc/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockClientRepository is an autogenerated mock type for the ClientRepository type
type MockClientRepository struct {
	mock.Mock
}

type MockClientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRepository) EXPECT() *MockClientRepository_Expecter {
	return &MockClientRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, c
func (_m *MockClientRepository) Create(ctx context.Context, c model.Client) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Client) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c model.Client
func (_e *MockClientRepository_Expecter) Create(ctx interface{}, c interface{}) *MockClientRepository_Create_Call {
	return &MockClientRepository_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *MockClientRepository_Create_Call) Run(run func(ctx context.Context, c model.Client)) *MockClientRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Client))
	})
	return _c
}

func (_c *MockClientRepository_Create_Call) Return(_a0 error) *MockClientRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientRepository_Create_Call) RunAndReturn(run func(context.Context, model.Client) error) *MockClientRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockClientRepository) Get(ctx context.Context, id string) (model.Client, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Client, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Client); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClientRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClientRepository_Expecter) Get(ctx interface{}, id interface{}) *MockClientRepository_Get_Call {
	return &MockClientRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockClientRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockClientRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClientRepository_Get_Call) Return(_a0 model.Client, _a1 error) *MockClientRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.Client, error)) *MockClientRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockClientRepository) List(ctx context.Context) ([]model.Client, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Client, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Client); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClientRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientRepository_Expecter) List(ctx interface{}) *MockClientRepository_List_Call {
	return &MockClientRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockClientRepository_List_Call) Run(run func(ctx context.Context)) *MockClientRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClientRepository_List_Call) Return(_a0 []model.Client, _a1 error) *MockClientRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepository_List_Call) RunAndReturn(run func(context.Context) ([]model.Client, error)) *MockClientRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id, at
func (_m *MockClientRepository) Revoke(ctx context.Context, id string, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockClientRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - at time.Time
func (_e *MockClientRepository_Expecter) Revoke(ctx interface{}, id interface{}, at interface{}) *MockClientRepository_Revoke_Call {
	return &MockClientRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, at)}
}

func (_c *MockClientRepository_Revoke_Call) Run(run func(ctx context.Context, id string, at time.Time)) *MockClientRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockClientRepository_Revoke_Call) Return(_a0 error) *MockClientRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientRepository_Revoke_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockClientRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, c
func (_m *MockClientRepository) Update(ctx context.Context, c model.Client) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Client) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClientRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c model.Client
func (_e *MockClientRepository_Expecter) Update(ctx interface{}, c interface{}) *MockClientRepository_Update_Call {
	return &MockClientRepository_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *MockClientRepository_Update_Call) Run(run func(ctx context.Context, c model.Client)) *MockClientRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Client))
	})
	return _c
}

func (_c *MockClientRepository_Update_Call) Return(_a0 error) *MockClientRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientRepository_Update_Call) RunAndReturn(run func(context.Context, model.Client) error) *MockClientRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientRepository creates a new instance of MockClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRepository {
	mock := &MockClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
