// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/oidc/model"
	mock "github.com/stretchr/testify/mock"
)

// MockKeyRepository is an autogenerated mock type for the KeyRepository type
type MockKeyRepository struct {
	mock.Mock
}

type MockKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyRepository) EXPECT() *MockKeyRepository_Expecter {
	return &MockKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, k
func (_m *MockKeyRepository) Create(ctx context.Context, k model.SigningKey) error {
	ret := _m.Called(ctx, k)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SigningKey) error); ok {
		r0 = rf(ctx, k)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - k model.SigningKey
func (_e *MockKeyRepository_Expecter) Create(ctx interface{}, k interface{}) *MockKeyRepository_Create_Call {
	return &MockKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, k)}
}

func (_c *MockKeyRepository_Create_Call) Run(run func(ctx context.Context, k model.SigningKey)) *MockKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SigningKey))
	})
	return _c
}

func (_c *MockKeyRepository_Create_Call) Return(_a0 error) *MockKeyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyRepository_Create_Call) RunAndReturn(run func(context.Context, model.SigningKey) error) *MockKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx
func (_m *MockKeyRepository) ListActive(ctx context.Context) ([]model.SigningKey, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []model.SigningKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SigningKey, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SigningKey); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SigningKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockKeyRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKeyRepository_Expecter) ListActive(ctx interface{}) *MockKeyRepository_ListActive_Call {
	return &MockKeyRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx)}
}

func (_c *MockKeyRepository_ListActive_Call) Run(run func(ctx context.Context)) *MockKeyRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockKeyRepository_ListActive_Call) Return(_a0 []model.SigningKey, _a1 error) *MockKeyRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyRepository_ListActive_Call) RunAndReturn(run func(context.Context) ([]model.SigningKey, error)) *MockKeyRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyRepository creates a new instance of MockKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyRepository {
	mock := &MockKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
