// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/listing/model"
	mock "github.com/stretchr/testify/mock"

	query "github.com/all-in-one/internal/query"
)

// MockItemRepository is an autogenerated mock type for the ItemRepository type
type MockItemRepository struct {
	mock.Mock
}

type MockItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemRepository) EXPECT() *MockItemRepository_Expecter {
	return &MockItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *MockItemRepository) Create(ctx context.Context, item model.Item) (model.Item, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Item) (model.Item, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Item) model.Item); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(model.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Item) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item model.Item
func (_e *MockItemRepository_Expecter) Create(ctx interface{}, item interface{}) *MockItemRepository_Create_Call {
	return &MockItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockItemRepository_Create_Call) Run(run func(ctx context.Context, item model.Item)) *MockItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Item))
	})
	return _c
}

func (_c *MockItemRepository_Create_Call) Return(_a0 model.Item, _a1 error) *MockItemRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_Create_Call) RunAndReturn(run func(context.Context, model.Item) (model.Item, error)) *MockItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockItemRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockItemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockItemRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockItemRepository_Delete_Call {
	return &MockItemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockItemRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockItemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockItemRepository_Delete_Call) Return(_a0 error) *MockItemRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockItemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTopicID provides a mock function with given fields: ctx, topicID, opts
func (_m *MockItemRepository) DeleteByTopicID(ctx context.Context, topicID int, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, topicID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTopicID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, topicID, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemRepository_DeleteByTopicID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTopicID'
type MockItemRepository_DeleteByTopicID_Call struct {
	*mock.Call
}

// DeleteByTopicID is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int
//   - opts ...query.QueryOptions
func (_e *MockItemRepository_Expecter) DeleteByTopicID(ctx interface{}, topicID interface{}, opts ...interface{}) *MockItemRepository_DeleteByTopicID_Call {
	return &MockItemRepository_DeleteByTopicID_Call{Call: _e.mock.On("DeleteByTopicID",
		append([]interface{}{ctx, topicID}, opts...)...)}
}

func (_c *MockItemRepository_DeleteByTopicID_Call) Run(run func(ctx context.Context, topicID int, opts ...query.QueryOptions)) *MockItemRepository_DeleteByTopicID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockItemRepository_DeleteByTopicID_Call) Return(_a0 error) *MockItemRepository_DeleteByTopicID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemRepository_DeleteByTopicID_Call) RunAndReturn(run func(context.Context, int, ...query.QueryOptions) error) *MockItemRepository_DeleteByTopicID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockItemRepository) Get(ctx context.Context, id int) (model.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (model.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) model.Item); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockItemRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockItemRepository_Expecter) Get(ctx interface{}, id interface{}) *MockItemRepository_Get_Call {
	return &MockItemRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockItemRepository_Get_Call) Run(run func(ctx context.Context, id int)) *MockItemRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockItemRepository_Get_Call) Return(_a0 model.Item, _a1 error) *MockItemRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_Get_Call) RunAndReturn(run func(context.Context, int) (model.Item, error)) *MockItemRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockItemRepository) GetAll(ctx context.Context) ([]model.Item, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Item, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Item); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockItemRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockItemRepository_Expecter) GetAll(ctx interface{}) *MockItemRepository_GetAll_Call {
	return &MockItemRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockItemRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockItemRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockItemRepository_GetAll_Call) Return(_a0 []model.Item, _a1 error) *MockItemRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]model.Item, error)) *MockItemRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTopicID provides a mock function with given fields: ctx, topicID
func (_m *MockItemRepository) GetByTopicID(ctx context.Context, topicID int) ([]model.Item, error) {
	ret := _m.Called(ctx, topicID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTopicID")
	}

	var r0 []model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.Item, error)); ok {
		return rf(ctx, topicID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Item); ok {
		r0 = rf(ctx, topicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, topicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_GetByTopicID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTopicID'
type MockItemRepository_GetByTopicID_Call struct {
	*mock.Call
}

// GetByTopicID is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int
func (_e *MockItemRepository_Expecter) GetByTopicID(ctx interface{}, topicID interface{}) *MockItemRepository_GetByTopicID_Call {
	return &MockItemRepository_GetByTopicID_Call{Call: _e.mock.On("GetByTopicID", ctx, topicID)}
}

func (_c *MockItemRepository_GetByTopicID_Call) Run(run func(ctx context.Context, topicID int)) *MockItemRepository_GetByTopicID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockItemRepository_GetByTopicID_Call) Return(_a0 []model.Item, _a1 error) *MockItemRepository_GetByTopicID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_GetByTopicID_Call) RunAndReturn(run func(context.Context, int) ([]model.Item, error)) *MockItemRepository_GetByTopicID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, item
func (_m *MockItemRepository) Update(ctx context.Context, id int, item model.Item) (model.Item, error) {
	ret := _m.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, model.Item) (model.Item, error)); ok {
		return rf(ctx, id, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, model.Item) model.Item); ok {
		r0 = rf(ctx, id, item)
	} else {
		r0 = ret.Get(0).(model.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, model.Item) error); ok {
		r1 = rf(ctx, id, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - item model.Item
func (_e *MockItemRepository_Expecter) Update(ctx interface{}, id interface{}, item interface{}) *MockItemRepository_Update_Call {
	return &MockItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, item)}
}

func (_c *MockItemRepository_Update_Call) Run(run func(ctx context.Context, id int, item model.Item)) *MockItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(model.Item))
	})
	return _c
}

func (_c *MockItemRepository_Update_Call) Return(_a0 model.Item, _a1 error) *MockItemRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_Update_Call) RunAndReturn(run func(context.Context, int, model.Item) (model.Item, error)) *MockItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemRepository creates a new instance of MockItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemRepository {
	mock := &MockItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
