// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	repository "github.com/all-in-one/internal/listing/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockStorage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Close() *MockStorage_Close_Call {
	return &MockStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorage_Close_Call) Run(run func()) *MockStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Close_Call) Return(_a0 error) *MockStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Close_Call) RunAndReturn(run func() error) *MockStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ItemRepo provides a mock function with no fields
func (_m *MockStorage) ItemRepo() repository.ItemRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ItemRepo")
	}

	var r0 repository.ItemRepository
	if rf, ok := ret.Get(0).(func() repository.ItemRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ItemRepository)
		}
	}

	return r0
}

// MockStorage_ItemRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ItemRepo'
type MockStorage_ItemRepo_Call struct {
	*mock.Call
}

// ItemRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) ItemRepo() *MockStorage_ItemRepo_Call {
	return &MockStorage_ItemRepo_Call{Call: _e.mock.On("ItemRepo")}
}

func (_c *MockStorage_ItemRepo_Call) Run(run func()) *MockStorage_ItemRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_ItemRepo_Call) Return(_a0 repository.ItemRepository) *MockStorage_ItemRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_ItemRepo_Call) RunAndReturn(run func() repository.ItemRepository) *MockStorage_ItemRepo_Call {
	_c.Call.Return(run)
	return _c
}

// TopicRepo provides a mock function with no fields
func (_m *MockStorage) TopicRepo() repository.TopicRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopicRepo")
	}

	var r0 repository.TopicRepository
	if rf, ok := ret.Get(0).(func() repository.TopicRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.TopicRepository)
		}
	}

	return r0
}

// MockStorage_TopicRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopicRepo'
type MockStorage_TopicRepo_Call struct {
	*mock.Call
}

// TopicRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) TopicRepo() *MockStorage_TopicRepo_Call {
	return &MockStorage_TopicRepo_Call{Call: _e.mock.On("TopicRepo")}
}

func (_c *MockStorage_TopicRepo_Call) Run(run func()) *MockStorage_TopicRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_TopicRepo_Call) Return(_a0 repository.TopicRepository) *MockStorage_TopicRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_TopicRepo_Call) RunAndReturn(run func() repository.TopicRepository) *MockStorage_TopicRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
