// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/listing/model"
	mock "github.com/stretchr/testify/mock"

	query "github.com/all-in-one/internal/query"

	uuid "github.com/google/uuid"
)

// MockTopicRepository is an autogenerated mock type for the TopicRepository type
type MockTopicRepository struct {
	mock.Mock
}

type MockTopicRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopicRepository) EXPECT() *MockTopicRepository_Expecter {
	return &MockTopicRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *MockTopicRepository) Create(ctx context.Context, item model.Topic) (model.Topic, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Topic) (model.Topic, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Topic) model.Topic); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(model.Topic)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Topic) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTopicRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item model.Topic
func (_e *MockTopicRepository_Expecter) Create(ctx interface{}, item interface{}) *MockTopicRepository_Create_Call {
	return &MockTopicRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockTopicRepository_Create_Call) Run(run func(ctx context.Context, item model.Topic)) *MockTopicRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Topic))
	})
	return _c
}

func (_c *MockTopicRepository_Create_Call) Return(_a0 model.Topic, _a1 error) *MockTopicRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_Create_Call) RunAndReturn(run func(context.Context, model.Topic) (model.Topic, error)) *MockTopicRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTrx provides a mock function with given fields: ctx
func (_m *MockTopicRepository) CreateTrx(ctx context.Context) (query.QueryOptions, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrx")
	}

	var r0 query.QueryOptions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (query.QueryOptions, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) query.QueryOptions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(query.QueryOptions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_CreateTrx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrx'
type MockTopicRepository_CreateTrx_Call struct {
	*mock.Call
}

// CreateTrx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTopicRepository_Expecter) CreateTrx(ctx interface{}) *MockTopicRepository_CreateTrx_Call {
	return &MockTopicRepository_CreateTrx_Call{Call: _e.mock.On("CreateTrx", ctx)}
}

func (_c *MockTopicRepository_CreateTrx_Call) Run(run func(ctx context.Context)) *MockTopicRepository_CreateTrx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTopicRepository_CreateTrx_Call) Return(_a0 query.QueryOptions, _a1 error) *MockTopicRepository_CreateTrx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_CreateTrx_Call) RunAndReturn(run func(context.Context) (query.QueryOptions, error)) *MockTopicRepository_CreateTrx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, opts
func (_m *MockTopicRepository) Delete(ctx context.Context, id int, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTopicRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTopicRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - opts ...query.QueryOptions
func (_e *MockTopicRepository_Expecter) Delete(ctx interface{}, id interface{}, opts ...interface{}) *MockTopicRepository_Delete_Call {
	return &MockTopicRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *MockTopicRepository_Delete_Call) Run(run func(ctx context.Context, id int, opts ...query.QueryOptions)) *MockTopicRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockTopicRepository_Delete_Call) Return(_a0 error) *MockTopicRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopicRepository_Delete_Call) RunAndReturn(run func(context.Context, int, ...query.QueryOptions) error) *MockTopicRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockTopicRepository) Get(ctx context.Context, id int) (model.Topic, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (model.Topic, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) model.Topic); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Topic)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTopicRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTopicRepository_Expecter) Get(ctx interface{}, id interface{}) *MockTopicRepository_Get_Call {
	return &MockTopicRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTopicRepository_Get_Call) Run(run func(ctx context.Context, id int)) *MockTopicRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTopicRepository_Get_Call) Return(_a0 model.Topic, _a1 error) *MockTopicRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_Get_Call) RunAndReturn(run func(context.Context, int) (model.Topic, error)) *MockTopicRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, userID
func (_m *MockTopicRepository) GetAll(ctx context.Context, userID uuid.UUID) ([]model.Topic, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Topic, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Topic); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTopicRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTopicRepository_Expecter) GetAll(ctx interface{}, userID interface{}) *MockTopicRepository_GetAll_Call {
	return &MockTopicRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, userID)}
}

func (_c *MockTopicRepository_GetAll_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTopicRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTopicRepository_GetAll_Call) Return(_a0 []model.Topic, _a1 error) *MockTopicRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_GetAll_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Topic, error)) *MockTopicRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, item
func (_m *MockTopicRepository) Update(ctx context.Context, id int, item model.Topic) (model.Topic, error) {
	ret := _m.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, model.Topic) (model.Topic, error)); ok {
		return rf(ctx, id, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, model.Topic) model.Topic); ok {
		r0 = rf(ctx, id, item)
	} else {
		r0 = ret.Get(0).(model.Topic)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, model.Topic) error); ok {
		r1 = rf(ctx, id, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTopicRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - item model.Topic
func (_e *MockTopicRepository_Expecter) Update(ctx interface{}, id interface{}, item interface{}) *MockTopicRepository_Update_Call {
	return &MockTopicRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, item)}
}

func (_c *MockTopicRepository_Update_Call) Run(run func(ctx context.Context, id int, item model.Topic)) *MockTopicRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(model.Topic))
	})
	return _c
}

func (_c *MockTopicRepository_Update_Call) Return(_a0 model.Topic, _a1 error) *MockTopicRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_Update_Call) RunAndReturn(run func(context.Context, int, model.Topic) (model.Topic, error)) *MockTopicRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTopicRepository creates a new instance of MockTopicRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopicRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopicRepository {
	mock := &MockTopicRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
