// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockQueryOptions is an autogenerated mock type for the QueryOptions type
type MockQueryOptions struct {
	mock.Mock
}

type MockQueryOptions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryOptions) EXPECT() *MockQueryOptions_Expecter {
	return &MockQueryOptions_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with no fields
func (_m *MockQueryOptions) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueryOptions_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockQueryOptions_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockQueryOptions_Expecter) Commit() *MockQueryOptions_Commit_Call {
	return &MockQueryOptions_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockQueryOptions_Commit_Call) Run(run func()) *MockQueryOptions_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryOptions_Commit_Call) Return(_a0 error) *MockQueryOptions_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueryOptions_Commit_Call) RunAndReturn(run func() error) *MockQueryOptions_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with no fields
func (_m *MockQueryOptions) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueryOptions_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockQueryOptions_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockQueryOptions_Expecter) Rollback() *MockQueryOptions_Rollback_Call {
	return &MockQueryOptions_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *MockQueryOptions_Rollback_Call) Run(run func()) *MockQueryOptions_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryOptions_Rollback_Call) Return(_a0 error) *MockQueryOptions_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueryOptions_Rollback_Call) RunAndReturn(run func() error) *MockQueryOptions_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryOptions creates a new instance of MockQueryOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryOptions {
	mock := &MockQueryOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
