// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/rbac/model"
	mock "github.com/stretchr/testify/mock"

	query "github.com/all-in-one/internal/query"

	uuid "github.com/google/uuid"
)

// MockUserGroupRepository is an autogenerated mock type for the UserGroupRepository type
type MockUserGroupRepository struct {
	mock.Mock
}

type MockUserGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserGroupRepository) EXPECT() *MockUserGroupRepository_Expecter {
	return &MockUserGroupRepository_Expecter{mock: &_m.Mock}
}

// AssignGroup provides a mock function with given fields: ctx, userID, groupID, opts
func (_m *MockUserGroupRepository) AssignGroup(ctx context.Context, userID uuid.UUID, groupID *uuid.UUID, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, userID, groupID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AssignGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, userID, groupID, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserGroupRepository_AssignGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignGroup'
type MockUserGroupRepository_AssignGroup_Call struct {
	*mock.Call
}

// AssignGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - groupID *uuid.UUID
//   - opts ...query.QueryOptions
func (_e *MockUserGroupRepository_Expecter) AssignGroup(ctx interface{}, userID interface{}, groupID interface{}, opts ...interface{}) *MockUserGroupRepository_AssignGroup_Call {
	return &MockUserGroupRepository_AssignGroup_Call{Call: _e.mock.On("AssignGroup",
		append([]interface{}{ctx, userID, groupID}, opts...)...)}
}

func (_c *MockUserGroupRepository_AssignGroup_Call) Run(run func(ctx context.Context, userID uuid.UUID, groupID *uuid.UUID, opts ...query.QueryOptions)) *MockUserGroupRepository_AssignGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*uuid.UUID), variadicArgs...)
	})
	return _c
}

func (_c *MockUserGroupRepository_AssignGroup_Call) Return(_a0 error) *MockUserGroupRepository_AssignGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserGroupRepository_AssignGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID, *uuid.UUID, ...query.QueryOptions) error) *MockUserGroupRepository_AssignGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CountByGroup provides a mock function with given fields: ctx, groupID
func (_m *MockUserGroupRepository) CountByGroup(ctx context.Context, groupID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for CountByGroup")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, groupID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserGroupRepository_CountByGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByGroup'
type MockUserGroupRepository_CountByGroup_Call struct {
	*mock.Call
}

// CountByGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockUserGroupRepository_Expecter) CountByGroup(ctx interface{}, groupID interface{}) *MockUserGroupRepository_CountByGroup_Call {
	return &MockUserGroupRepository_CountByGroup_Call{Call: _e.mock.On("CountByGroup", ctx, groupID)}
}

func (_c *MockUserGroupRepository_CountByGroup_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockUserGroupRepository_CountByGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserGroupRepository_CountByGroup_Call) Return(_a0 int, _a1 error) *MockUserGroupRepository_CountByGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserGroupRepository_CountByGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockUserGroupRepository_CountByGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupID provides a mock function with given fields: ctx, userID
func (_m *MockUserGroupRepository) GetGroupID(ctx context.Context, userID uuid.UUID) (*uuid.UUID, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupID")
	}

	var r0 *uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*uuid.UUID, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *uuid.UUID); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserGroupRepository_GetGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupID'
type MockUserGroupRepository_GetGroupID_Call struct {
	*mock.Call
}

// GetGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserGroupRepository_Expecter) GetGroupID(ctx interface{}, userID interface{}) *MockUserGroupRepository_GetGroupID_Call {
	return &MockUserGroupRepository_GetGroupID_Call{Call: _e.mock.On("GetGroupID", ctx, userID)}
}

func (_c *MockUserGroupRepository_GetGroupID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserGroupRepository_GetGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserGroupRepository_GetGroupID_Call) Return(_a0 *uuid.UUID, _a1 error) *MockUserGroupRepository_GetGroupID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserGroupRepository_GetGroupID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*uuid.UUID, error)) *MockUserGroupRepository_GetGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsersWithGroup provides a mock function with given fields: ctx
func (_m *MockUserGroupRepository) ListUsersWithGroup(ctx context.Context) ([]model.UserAccessRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersWithGroup")
	}

	var r0 []model.UserAccessRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.UserAccessRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.UserAccessRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserAccessRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserGroupRepository_ListUsersWithGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsersWithGroup'
type MockUserGroupRepository_ListUsersWithGroup_Call struct {
	*mock.Call
}

// ListUsersWithGroup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserGroupRepository_Expecter) ListUsersWithGroup(ctx interface{}) *MockUserGroupRepository_ListUsersWithGroup_Call {
	return &MockUserGroupRepository_ListUsersWithGroup_Call{Call: _e.mock.On("ListUsersWithGroup", ctx)}
}

func (_c *MockUserGroupRepository_ListUsersWithGroup_Call) Run(run func(ctx context.Context)) *MockUserGroupRepository_ListUsersWithGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserGroupRepository_ListUsersWithGroup_Call) Return(_a0 []model.UserAccessRow, _a1 error) *MockUserGroupRepository_ListUsersWithGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserGroupRepository_ListUsersWithGroup_Call) RunAndReturn(run func(context.Context) ([]model.UserAccessRow, error)) *MockUserGroupRepository_ListUsersWithGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserGroupRepository creates a new instance of MockUserGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserGroupRepository {
	mock := &MockUserGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
