// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/rbac/model"
	mock "github.com/stretchr/testify/mock"

	query "github.com/all-in-one/internal/query"

	uuid "github.com/google/uuid"
)

// MockOverrideRepository is an autogenerated mock type for the OverrideRepository type
type MockOverrideRepository struct {
	mock.Mock
}

type MockOverrideRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOverrideRepository) EXPECT() *MockOverrideRepository_Expecter {
	return &MockOverrideRepository_Expecter{mock: &_m.Mock}
}

// GetByKey provides a mock function with given fields: ctx, userID, key
func (_m *MockOverrideRepository) GetByKey(ctx context.Context, userID uuid.UUID, key string) (*model.UserFeatureOverride, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 *model.UserFeatureOverride
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.UserFeatureOverride, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.UserFeatureOverride); ok {
		r0 = rf(ctx, userID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserFeatureOverride)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOverrideRepository_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockOverrideRepository_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - key string
func (_e *MockOverrideRepository_Expecter) GetByKey(ctx interface{}, userID interface{}, key interface{}) *MockOverrideRepository_GetByKey_Call {
	return &MockOverrideRepository_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, userID, key)}
}

func (_c *MockOverrideRepository_GetByKey_Call) Run(run func(ctx context.Context, userID uuid.UUID, key string)) *MockOverrideRepository_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockOverrideRepository_GetByKey_Call) Return(_a0 *model.UserFeatureOverride, _a1 error) *MockOverrideRepository_GetByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOverrideRepository_GetByKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*model.UserFeatureOverride, error)) *MockOverrideRepository_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockOverrideRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]model.UserFeatureOverride, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.UserFeatureOverride
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.UserFeatureOverride, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.UserFeatureOverride); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserFeatureOverride)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOverrideRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockOverrideRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockOverrideRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockOverrideRepository_ListByUser_Call {
	return &MockOverrideRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockOverrideRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockOverrideRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOverrideRepository_ListByUser_Call) Return(_a0 []model.UserFeatureOverride, _a1 error) *MockOverrideRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOverrideRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.UserFeatureOverride, error)) *MockOverrideRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceForUser provides a mock function with given fields: ctx, userID, overrides, opts
func (_m *MockOverrideRepository) ReplaceForUser(ctx context.Context, userID uuid.UUID, overrides []model.UserFeatureOverride, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, userID, overrides)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []model.UserFeatureOverride, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, userID, overrides, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOverrideRepository_ReplaceForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceForUser'
type MockOverrideRepository_ReplaceForUser_Call struct {
	*mock.Call
}

// ReplaceForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - overrides []model.UserFeatureOverride
//   - opts ...query.QueryOptions
func (_e *MockOverrideRepository_Expecter) ReplaceForUser(ctx interface{}, userID interface{}, overrides interface{}, opts ...interface{}) *MockOverrideRepository_ReplaceForUser_Call {
	return &MockOverrideRepository_ReplaceForUser_Call{Call: _e.mock.On("ReplaceForUser",
		append([]interface{}{ctx, userID, overrides}, opts...)...)}
}

func (_c *MockOverrideRepository_ReplaceForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, overrides []model.UserFeatureOverride, opts ...query.QueryOptions)) *MockOverrideRepository_ReplaceForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]model.UserFeatureOverride), variadicArgs...)
	})
	return _c
}

func (_c *MockOverrideRepository_ReplaceForUser_Call) Return(_a0 error) *MockOverrideRepository_ReplaceForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOverrideRepository_ReplaceForUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, []model.UserFeatureOverride, ...query.QueryOptions) error) *MockOverrideRepository_ReplaceForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOverrideRepository creates a new instance of MockOverrideRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOverrideRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOverrideRepository {
	mock := &MockOverrideRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
