// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/all-in-one/internal/query"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/all-in-one/internal/rbac/repository"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockStorage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Close() *MockStorage_Close_Call {
	return &MockStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorage_Close_Call) Run(run func()) *MockStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Close_Call) Return(_a0 error) *MockStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Close_Call) RunAndReturn(run func() error) *MockStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTrx provides a mock function with given fields: ctx
func (_m *MockStorage) CreateTrx(ctx context.Context) (query.QueryOptions, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrx")
	}

	var r0 query.QueryOptions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (query.QueryOptions, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) query.QueryOptions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(query.QueryOptions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateTrx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrx'
type MockStorage_CreateTrx_Call struct {
	*mock.Call
}

// CreateTrx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) CreateTrx(ctx interface{}) *MockStorage_CreateTrx_Call {
	return &MockStorage_CreateTrx_Call{Call: _e.mock.On("CreateTrx", ctx)}
}

func (_c *MockStorage_CreateTrx_Call) Run(run func(ctx context.Context)) *MockStorage_CreateTrx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_CreateTrx_Call) Return(_a0 query.QueryOptions, _a1 error) *MockStorage_CreateTrx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateTrx_Call) RunAndReturn(run func(context.Context) (query.QueryOptions, error)) *MockStorage_CreateTrx_Call {
	_c.Call.Return(run)
	return _c
}

// FeatureRepo provides a mock function with no fields
func (_m *MockStorage) FeatureRepo() repository.FeatureRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FeatureRepo")
	}

	var r0 repository.FeatureRepository
	if rf, ok := ret.Get(0).(func() repository.FeatureRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.FeatureRepository)
		}
	}

	return r0
}

// MockStorage_FeatureRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FeatureRepo'
type MockStorage_FeatureRepo_Call struct {
	*mock.Call
}

// FeatureRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) FeatureRepo() *MockStorage_FeatureRepo_Call {
	return &MockStorage_FeatureRepo_Call{Call: _e.mock.On("FeatureRepo")}
}

func (_c *MockStorage_FeatureRepo_Call) Run(run func()) *MockStorage_FeatureRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_FeatureRepo_Call) Return(_a0 repository.FeatureRepository) *MockStorage_FeatureRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_FeatureRepo_Call) RunAndReturn(run func() repository.FeatureRepository) *MockStorage_FeatureRepo_Call {
	_c.Call.Return(run)
	return _c
}

// GroupFeatureRepo provides a mock function with no fields
func (_m *MockStorage) GroupFeatureRepo() repository.GroupFeatureRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupFeatureRepo")
	}

	var r0 repository.GroupFeatureRepository
	if rf, ok := ret.Get(0).(func() repository.GroupFeatureRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.GroupFeatureRepository)
		}
	}

	return r0
}

// MockStorage_GroupFeatureRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupFeatureRepo'
type MockStorage_GroupFeatureRepo_Call struct {
	*mock.Call
}

// GroupFeatureRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) GroupFeatureRepo() *MockStorage_GroupFeatureRepo_Call {
	return &MockStorage_GroupFeatureRepo_Call{Call: _e.mock.On("GroupFeatureRepo")}
}

func (_c *MockStorage_GroupFeatureRepo_Call) Run(run func()) *MockStorage_GroupFeatureRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_GroupFeatureRepo_Call) Return(_a0 repository.GroupFeatureRepository) *MockStorage_GroupFeatureRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_GroupFeatureRepo_Call) RunAndReturn(run func() repository.GroupFeatureRepository) *MockStorage_GroupFeatureRepo_Call {
	_c.Call.Return(run)
	return _c
}

// GroupRepo provides a mock function with no fields
func (_m *MockStorage) GroupRepo() repository.GroupRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupRepo")
	}

	var r0 repository.GroupRepository
	if rf, ok := ret.Get(0).(func() repository.GroupRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.GroupRepository)
		}
	}

	return r0
}

// MockStorage_GroupRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupRepo'
type MockStorage_GroupRepo_Call struct {
	*mock.Call
}

// GroupRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) GroupRepo() *MockStorage_GroupRepo_Call {
	return &MockStorage_GroupRepo_Call{Call: _e.mock.On("GroupRepo")}
}

func (_c *MockStorage_GroupRepo_Call) Run(run func()) *MockStorage_GroupRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_GroupRepo_Call) Return(_a0 repository.GroupRepository) *MockStorage_GroupRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_GroupRepo_Call) RunAndReturn(run func() repository.GroupRepository) *MockStorage_GroupRepo_Call {
	_c.Call.Return(run)
	return _c
}

// OverrideRepo provides a mock function with no fields
func (_m *MockStorage) OverrideRepo() repository.OverrideRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OverrideRepo")
	}

	var r0 repository.OverrideRepository
	if rf, ok := ret.Get(0).(func() repository.OverrideRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.OverrideRepository)
		}
	}

	return r0
}

// MockStorage_OverrideRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OverrideRepo'
type MockStorage_OverrideRepo_Call struct {
	*mock.Call
}

// OverrideRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) OverrideRepo() *MockStorage_OverrideRepo_Call {
	return &MockStorage_OverrideRepo_Call{Call: _e.mock.On("OverrideRepo")}
}

func (_c *MockStorage_OverrideRepo_Call) Run(run func()) *MockStorage_OverrideRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_OverrideRepo_Call) Return(_a0 repository.OverrideRepository) *MockStorage_OverrideRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_OverrideRepo_Call) RunAndReturn(run func() repository.OverrideRepository) *MockStorage_OverrideRepo_Call {
	_c.Call.Return(run)
	return _c
}

// UserGroupRepo provides a mock function with no fields
func (_m *MockStorage) UserGroupRepo() repository.UserGroupRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserGroupRepo")
	}

	var r0 repository.UserGroupRepository
	if rf, ok := ret.Get(0).(func() repository.UserGroupRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserGroupRepository)
		}
	}

	return r0
}

// MockStorage_UserGroupRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGroupRepo'
type MockStorage_UserGroupRepo_Call struct {
	*mock.Call
}

// UserGroupRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) UserGroupRepo() *MockStorage_UserGroupRepo_Call {
	return &MockStorage_UserGroupRepo_Call{Call: _e.mock.On("UserGroupRepo")}
}

func (_c *MockStorage_UserGroupRepo_Call) Run(run func()) *MockStorage_UserGroupRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_UserGroupRepo_Call) Return(_a0 repository.UserGroupRepository) *MockStorage_UserGroupRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UserGroupRepo_Call) RunAndReturn(run func() repository.UserGroupRepository) *MockStorage_UserGroupRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
