// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/rbac/model"
	mock "github.com/stretchr/testify/mock"

	query "github.com/all-in-one/internal/query"

	uuid "github.com/google/uuid"
)

// MockGroupRepository is an autogenerated mock type for the GroupRepository type
type MockGroupRepository struct {
	mock.Mock
}

type MockGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupRepository) EXPECT() *MockGroupRepository_Expecter {
	return &MockGroupRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, group, opts
func (_m *MockGroupRepository) Create(ctx context.Context, group model.Group, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, group)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Group, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, group, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - group model.Group
//   - opts ...query.QueryOptions
func (_e *MockGroupRepository_Expecter) Create(ctx interface{}, group interface{}, opts ...interface{}) *MockGroupRepository_Create_Call {
	return &MockGroupRepository_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, group}, opts...)...)}
}

func (_c *MockGroupRepository_Create_Call) Run(run func(ctx context.Context, group model.Group, opts ...query.QueryOptions)) *MockGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(model.Group), variadicArgs...)
	})
	return _c
}

func (_c *MockGroupRepository_Create_Call) Return(_a0 error) *MockGroupRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_Create_Call) RunAndReturn(run func(context.Context, model.Group, ...query.QueryOptions) error) *MockGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, opts
func (_m *MockGroupRepository) Delete(ctx context.Context, id uuid.UUID, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGroupRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - opts ...query.QueryOptions
func (_e *MockGroupRepository_Expecter) Delete(ctx interface{}, id interface{}, opts ...interface{}) *MockGroupRepository_Delete_Call {
	return &MockGroupRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *MockGroupRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, opts ...query.QueryOptions)) *MockGroupRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), variadicArgs...)
	})
	return _c
}

func (_c *MockGroupRepository_Delete_Call) Return(_a0 error) *MockGroupRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, ...query.QueryOptions) error) *MockGroupRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureBuiltin provides a mock function with given fields: ctx, name, description
func (_m *MockGroupRepository) EnsureBuiltin(ctx context.Context, name string, description string) (model.Group, error) {
	ret := _m.Called(ctx, name, description)

	if len(ret) == 0 {
		panic("no return value specified for EnsureBuiltin")
	}

	var r0 model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.Group, error)); ok {
		return rf(ctx, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.Group); ok {
		r0 = rf(ctx, name, description)
	} else {
		r0 = ret.Get(0).(model.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_EnsureBuiltin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureBuiltin'
type MockGroupRepository_EnsureBuiltin_Call struct {
	*mock.Call
}

// EnsureBuiltin is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
func (_e *MockGroupRepository_Expecter) EnsureBuiltin(ctx interface{}, name interface{}, description interface{}) *MockGroupRepository_EnsureBuiltin_Call {
	return &MockGroupRepository_EnsureBuiltin_Call{Call: _e.mock.On("EnsureBuiltin", ctx, name, description)}
}

func (_c *MockGroupRepository_EnsureBuiltin_Call) Run(run func(ctx context.Context, name string, description string)) *MockGroupRepository_EnsureBuiltin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupRepository_EnsureBuiltin_Call) Return(_a0 model.Group, _a1 error) *MockGroupRepository_EnsureBuiltin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_EnsureBuiltin_Call) RunAndReturn(run func(context.Context, string, string) (model.Group, error)) *MockGroupRepository_EnsureBuiltin_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockGroupRepository) Get(ctx context.Context, id uuid.UUID) (model.Group, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Group, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Group); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGroupRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGroupRepository_Expecter) Get(ctx interface{}, id interface{}) *MockGroupRepository_Get_Call {
	return &MockGroupRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockGroupRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGroupRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupRepository_Get_Call) Return(_a0 model.Group, _a1 error) *MockGroupRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Group, error)) *MockGroupRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockGroupRepository) GetByName(ctx context.Context, name string) (model.Group, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Group, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Group); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockGroupRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockGroupRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockGroupRepository_GetByName_Call {
	return &MockGroupRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockGroupRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockGroupRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupRepository_GetByName_Call) Return(_a0 model.Group, _a1 error) *MockGroupRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (model.Group, error)) *MockGroupRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockGroupRepository) List(ctx context.Context) ([]model.Group, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Group, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Group); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGroupRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGroupRepository_Expecter) List(ctx interface{}) *MockGroupRepository_List_Call {
	return &MockGroupRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockGroupRepository_List_Call) Run(run func(ctx context.Context)) *MockGroupRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGroupRepository_List_Call) Return(_a0 []model.Group, _a1 error) *MockGroupRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_List_Call) RunAndReturn(run func(context.Context) ([]model.Group, error)) *MockGroupRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, group, opts
func (_m *MockGroupRepository) Update(ctx context.Context, group model.Group, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, group)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Group, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, group, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGroupRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - group model.Group
//   - opts ...query.QueryOptions
func (_e *MockGroupRepository_Expecter) Update(ctx interface{}, group interface{}, opts ...interface{}) *MockGroupRepository_Update_Call {
	return &MockGroupRepository_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, group}, opts...)...)}
}

func (_c *MockGroupRepository_Update_Call) Run(run func(ctx context.Context, group model.Group, opts ...query.QueryOptions)) *MockGroupRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(model.Group), variadicArgs...)
	})
	return _c
}

func (_c *MockGroupRepository_Update_Call) Return(_a0 error) *MockGroupRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_Update_Call) RunAndReturn(run func(context.Context, model.Group, ...query.QueryOptions) error) *MockGroupRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupRepository creates a new instance of MockGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupRepository {
	mock := &MockGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
