// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/all-in-one/internal/query"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGroupFeatureRepository is an autogenerated mock type for the GroupFeatureRepository type
type MockGroupFeatureRepository struct {
	mock.Mock
}

type MockGroupFeatureRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupFeatureRepository) EXPECT() *MockGroupFeatureRepository_Expecter {
	return &MockGroupFeatureRepository_Expecter{mock: &_m.Mock}
}

// Grant provides a mock function with given fields: ctx, groupID, featureID, opts
func (_m *MockGroupFeatureRepository) Grant(ctx context.Context, groupID uuid.UUID, featureID uuid.UUID, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, groupID, featureID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Grant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, groupID, featureID, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupFeatureRepository_Grant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Grant'
type MockGroupFeatureRepository_Grant_Call struct {
	*mock.Call
}

// Grant is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - featureID uuid.UUID
//   - opts ...query.QueryOptions
func (_e *MockGroupFeatureRepository_Expecter) Grant(ctx interface{}, groupID interface{}, featureID interface{}, opts ...interface{}) *MockGroupFeatureRepository_Grant_Call {
	return &MockGroupFeatureRepository_Grant_Call{Call: _e.mock.On("Grant",
		append([]interface{}{ctx, groupID, featureID}, opts...)...)}
}

func (_c *MockGroupFeatureRepository_Grant_Call) Run(run func(ctx context.Context, groupID uuid.UUID, featureID uuid.UUID, opts ...query.QueryOptions)) *MockGroupFeatureRepository_Grant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), variadicArgs...)
	})
	return _c
}

func (_c *MockGroupFeatureRepository_Grant_Call) Return(_a0 error) *MockGroupFeatureRepository_Grant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupFeatureRepository_Grant_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, ...query.QueryOptions) error) *MockGroupFeatureRepository_Grant_Call {
	_c.Call.Return(run)
	return _c
}

// HasGrantByKey provides a mock function with given fields: ctx, groupID, key
func (_m *MockGroupFeatureRepository) HasGrantByKey(ctx context.Context, groupID uuid.UUID, key string) (bool, error) {
	ret := _m.Called(ctx, groupID, key)

	if len(ret) == 0 {
		panic("no return value specified for HasGrantByKey")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return rf(ctx, groupID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = rf(ctx, groupID, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, groupID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupFeatureRepository_HasGrantByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasGrantByKey'
type MockGroupFeatureRepository_HasGrantByKey_Call struct {
	*mock.Call
}

// HasGrantByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - key string
func (_e *MockGroupFeatureRepository_Expecter) HasGrantByKey(ctx interface{}, groupID interface{}, key interface{}) *MockGroupFeatureRepository_HasGrantByKey_Call {
	return &MockGroupFeatureRepository_HasGrantByKey_Call{Call: _e.mock.On("HasGrantByKey", ctx, groupID, key)}
}

func (_c *MockGroupFeatureRepository_HasGrantByKey_Call) Run(run func(ctx context.Context, groupID uuid.UUID, key string)) *MockGroupFeatureRepository_HasGrantByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockGroupFeatureRepository_HasGrantByKey_Call) Return(_a0 bool, _a1 error) *MockGroupFeatureRepository_HasGrantByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupFeatureRepository_HasGrantByKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (bool, error)) *MockGroupFeatureRepository_HasGrantByKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeysByGroup provides a mock function with given fields: ctx, groupID
func (_m *MockGroupFeatureRepository) ListKeysByGroup(ctx context.Context, groupID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ListKeysByGroup")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupFeatureRepository_ListKeysByGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeysByGroup'
type MockGroupFeatureRepository_ListKeysByGroup_Call struct {
	*mock.Call
}

// ListKeysByGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockGroupFeatureRepository_Expecter) ListKeysByGroup(ctx interface{}, groupID interface{}) *MockGroupFeatureRepository_ListKeysByGroup_Call {
	return &MockGroupFeatureRepository_ListKeysByGroup_Call{Call: _e.mock.On("ListKeysByGroup", ctx, groupID)}
}

func (_c *MockGroupFeatureRepository_ListKeysByGroup_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockGroupFeatureRepository_ListKeysByGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupFeatureRepository_ListKeysByGroup_Call) Return(_a0 []string, _a1 error) *MockGroupFeatureRepository_ListKeysByGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupFeatureRepository_ListKeysByGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *MockGroupFeatureRepository_ListKeysByGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceGrants provides a mock function with given fields: ctx, groupID, featureIDs, opts
func (_m *MockGroupFeatureRepository) ReplaceGrants(ctx context.Context, groupID uuid.UUID, featureIDs []uuid.UUID, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, groupID, featureIDs)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceGrants")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, groupID, featureIDs, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupFeatureRepository_ReplaceGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceGrants'
type MockGroupFeatureRepository_ReplaceGrants_Call struct {
	*mock.Call
}

// ReplaceGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - featureIDs []uuid.UUID
//   - opts ...query.QueryOptions
func (_e *MockGroupFeatureRepository_Expecter) ReplaceGrants(ctx interface{}, groupID interface{}, featureIDs interface{}, opts ...interface{}) *MockGroupFeatureRepository_ReplaceGrants_Call {
	return &MockGroupFeatureRepository_ReplaceGrants_Call{Call: _e.mock.On("ReplaceGrants",
		append([]interface{}{ctx, groupID, featureIDs}, opts...)...)}
}

func (_c *MockGroupFeatureRepository_ReplaceGrants_Call) Run(run func(ctx context.Context, groupID uuid.UUID, featureIDs []uuid.UUID, opts ...query.QueryOptions)) *MockGroupFeatureRepository_ReplaceGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]uuid.UUID), variadicArgs...)
	})
	return _c
}

func (_c *MockGroupFeatureRepository_ReplaceGrants_Call) Return(_a0 error) *MockGroupFeatureRepository_ReplaceGrants_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupFeatureRepository_ReplaceGrants_Call) RunAndReturn(run func(context.Context, uuid.UUID, []uuid.UUID, ...query.QueryOptions) error) *MockGroupFeatureRepository_ReplaceGrants_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupFeatureRepository creates a new instance of MockGroupFeatureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupFeatureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupFeatureRepository {
	mock := &MockGroupFeatureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
