// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/rbac/model"
	mock "github.com/stretchr/testify/mock"
)

// MockFeatureRepository is an autogenerated mock type for the FeatureRepository type
type MockFeatureRepository struct {
	mock.Mock
}

type MockFeatureRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureRepository) EXPECT() *MockFeatureRepository_Expecter {
	return &MockFeatureRepository_Expecter{mock: &_m.Mock}
}

// GetByKey provides a mock function with given fields: ctx, key
func (_m *MockFeatureRepository) GetByKey(ctx context.Context, key string) (model.Feature, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 model.Feature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Feature, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Feature); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(model.Feature)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeatureRepository_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockFeatureRepository_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFeatureRepository_Expecter) GetByKey(ctx interface{}, key interface{}) *MockFeatureRepository_GetByKey_Call {
	return &MockFeatureRepository_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, key)}
}

func (_c *MockFeatureRepository_GetByKey_Call) Run(run func(ctx context.Context, key string)) *MockFeatureRepository_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFeatureRepository_GetByKey_Call) Return(_a0 model.Feature, _a1 error) *MockFeatureRepository_GetByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeatureRepository_GetByKey_Call) RunAndReturn(run func(context.Context, string) (model.Feature, error)) *MockFeatureRepository_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockFeatureRepository) List(ctx context.Context) ([]model.Feature, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Feature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Feature, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Feature); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Feature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeatureRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFeatureRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFeatureRepository_Expecter) List(ctx interface{}) *MockFeatureRepository_List_Call {
	return &MockFeatureRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockFeatureRepository_List_Call) Run(run func(ctx context.Context)) *MockFeatureRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFeatureRepository_List_Call) Return(_a0 []model.Feature, _a1 error) *MockFeatureRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeatureRepository_List_Call) RunAndReturn(run func(context.Context) ([]model.Feature, error)) *MockFeatureRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, feature
func (_m *MockFeatureRepository) Upsert(ctx context.Context, feature model.Feature) error {
	ret := _m.Called(ctx, feature)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Feature) error); ok {
		r0 = rf(ctx, feature)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeatureRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockFeatureRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - feature model.Feature
func (_e *MockFeatureRepository_Expecter) Upsert(ctx interface{}, feature interface{}) *MockFeatureRepository_Upsert_Call {
	return &MockFeatureRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, feature)}
}

func (_c *MockFeatureRepository_Upsert_Call) Run(run func(ctx context.Context, feature model.Feature)) *MockFeatureRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Feature))
	})
	return _c
}

func (_c *MockFeatureRepository_Upsert_Call) Return(_a0 error) *MockFeatureRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeatureRepository_Upsert_Call) RunAndReturn(run func(context.Context, model.Feature) error) *MockFeatureRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeatureRepository creates a new instance of MockFeatureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeatureRepository {
	mock := &MockFeatureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
