// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/all-in-one/internal/rbac/model"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AssignUserGroup provides a mock function with given fields: ctx, userID, groupID
func (_m *MockService) AssignUserGroup(ctx context.Context, userID uuid.UUID, groupID *uuid.UUID) error {
	ret := _m.Called(ctx, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for AssignUserGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r0 = rf(ctx, userID, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_AssignUserGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignUserGroup'
type MockService_AssignUserGroup_Call struct {
	*mock.Call
}

// AssignUserGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - groupID *uuid.UUID
func (_e *MockService_Expecter) AssignUserGroup(ctx interface{}, userID interface{}, groupID interface{}) *MockService_AssignUserGroup_Call {
	return &MockService_AssignUserGroup_Call{Call: _e.mock.On("AssignUserGroup", ctx, userID, groupID)}
}

func (_c *MockService_AssignUserGroup_Call) Run(run func(ctx context.Context, userID uuid.UUID, groupID *uuid.UUID)) *MockService_AssignUserGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*uuid.UUID))
	})
	return _c
}

func (_c *MockService_AssignUserGroup_Call) Return(_a0 error) *MockService_AssignUserGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_AssignUserGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID, *uuid.UUID) error) *MockService_AssignUserGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function with given fields: ctx, name, description, featureKeys
func (_m *MockService) CreateGroup(ctx context.Context, name string, description string, featureKeys []string) (model.Group, error) {
	ret := _m.Called(ctx, name, description, featureKeys)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) (model.Group, error)); ok {
		return rf(ctx, name, description, featureKeys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) model.Group); ok {
		r0 = rf(ctx, name, description, featureKeys)
	} else {
		r0 = ret.Get(0).(model.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = rf(ctx, name, description, featureKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockService_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
//   - featureKeys []string
func (_e *MockService_Expecter) CreateGroup(ctx interface{}, name interface{}, description interface{}, featureKeys interface{}) *MockService_CreateGroup_Call {
	return &MockService_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, name, description, featureKeys)}
}

func (_c *MockService_CreateGroup_Call) Run(run func(ctx context.Context, name string, description string, featureKeys []string)) *MockService_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockService_CreateGroup_Call) Return(_a0 model.Group, _a1 error) *MockService_CreateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateGroup_Call) RunAndReturn(run func(context.Context, string, string, []string) (model.Group, error)) *MockService_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockService_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) DeleteGroup(ctx interface{}, id interface{}) *MockService_DeleteGroup_Call {
	return &MockService_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, id)}
}

func (_c *MockService_DeleteGroup_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_DeleteGroup_Call) Return(_a0 error) *MockService_DeleteGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockService_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroup provides a mock function with given fields: ctx, id
func (_m *MockService) GetGroup(ctx context.Context, id uuid.UUID) (model.Group, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Group, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Group); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroup'
type MockService_GetGroup_Call struct {
	*mock.Call
}

// GetGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) GetGroup(ctx interface{}, id interface{}) *MockService_GetGroup_Call {
	return &MockService_GetGroup_Call{Call: _e.mock.On("GetGroup", ctx, id)}
}

func (_c *MockService_GetGroup_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_GetGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetGroup_Call) Return(_a0 model.Group, _a1 error) *MockService_GetGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Group, error)) *MockService_GetGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListFeatures provides a mock function with given fields: ctx
func (_m *MockService) ListFeatures(ctx context.Context) ([]model.Feature, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListFeatures")
	}

	var r0 []model.Feature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Feature, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Feature); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Feature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFeatures'
type MockService_ListFeatures_Call struct {
	*mock.Call
}

// ListFeatures is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListFeatures(ctx interface{}) *MockService_ListFeatures_Call {
	return &MockService_ListFeatures_Call{Call: _e.mock.On("ListFeatures", ctx)}
}

func (_c *MockService_ListFeatures_Call) Run(run func(ctx context.Context)) *MockService_ListFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListFeatures_Call) Return(_a0 []model.Feature, _a1 error) *MockService_ListFeatures_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListFeatures_Call) RunAndReturn(run func(context.Context) ([]model.Feature, error)) *MockService_ListFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroups provides a mock function with given fields: ctx
func (_m *MockService) ListGroups(ctx context.Context) ([]model.Group, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGroups")
	}

	var r0 []model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Group, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Group); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroups'
type MockService_ListGroups_Call struct {
	*mock.Call
}

// ListGroups is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListGroups(ctx interface{}) *MockService_ListGroups_Call {
	return &MockService_ListGroups_Call{Call: _e.mock.On("ListGroups", ctx)}
}

func (_c *MockService_ListGroups_Call) Run(run func(ctx context.Context)) *MockService_ListGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListGroups_Call) Return(_a0 []model.Group, _a1 error) *MockService_ListGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListGroups_Call) RunAndReturn(run func(context.Context) ([]model.Group, error)) *MockService_ListGroups_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserOverrides provides a mock function with given fields: ctx, userID
func (_m *MockService) ListUserOverrides(ctx context.Context, userID uuid.UUID) ([]model.FeatureOverrideView, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserOverrides")
	}

	var r0 []model.FeatureOverrideView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.FeatureOverrideView, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.FeatureOverrideView); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.FeatureOverrideView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListUserOverrides_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserOverrides'
type MockService_ListUserOverrides_Call struct {
	*mock.Call
}

// ListUserOverrides is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) ListUserOverrides(ctx interface{}, userID interface{}) *MockService_ListUserOverrides_Call {
	return &MockService_ListUserOverrides_Call{Call: _e.mock.On("ListUserOverrides", ctx, userID)}
}

func (_c *MockService_ListUserOverrides_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_ListUserOverrides_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_ListUserOverrides_Call) Return(_a0 []model.FeatureOverrideView, _a1 error) *MockService_ListUserOverrides_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListUserOverrides_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.FeatureOverrideView, error)) *MockService_ListUserOverrides_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *MockService) ListUsers(ctx context.Context) ([]model.UserAccessRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []model.UserAccessRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.UserAccessRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.UserAccessRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserAccessRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListUsers(ctx interface{}) *MockService_ListUsers_Call {
	return &MockService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *MockService_ListUsers_Call) Run(run func(ctx context.Context)) *MockService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListUsers_Call) Return(_a0 []model.UserAccessRow, _a1 error) *MockService_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListUsers_Call) RunAndReturn(run func(context.Context) ([]model.UserAccessRow, error)) *MockService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SetGroupFeatures provides a mock function with given fields: ctx, id, featureKeys
func (_m *MockService) SetGroupFeatures(ctx context.Context, id uuid.UUID, featureKeys []string) (model.Group, error) {
	ret := _m.Called(ctx, id, featureKeys)

	if len(ret) == 0 {
		panic("no return value specified for SetGroupFeatures")
	}

	var r0 model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) (model.Group, error)); ok {
		return rf(ctx, id, featureKeys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) model.Group); ok {
		r0 = rf(ctx, id, featureKeys)
	} else {
		r0 = ret.Get(0).(model.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = rf(ctx, id, featureKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SetGroupFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGroupFeatures'
type MockService_SetGroupFeatures_Call struct {
	*mock.Call
}

// SetGroupFeatures is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - featureKeys []string
func (_e *MockService_Expecter) SetGroupFeatures(ctx interface{}, id interface{}, featureKeys interface{}) *MockService_SetGroupFeatures_Call {
	return &MockService_SetGroupFeatures_Call{Call: _e.mock.On("SetGroupFeatures", ctx, id, featureKeys)}
}

func (_c *MockService_SetGroupFeatures_Call) Run(run func(ctx context.Context, id uuid.UUID, featureKeys []string)) *MockService_SetGroupFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockService_SetGroupFeatures_Call) Return(_a0 model.Group, _a1 error) *MockService_SetGroupFeatures_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_SetGroupFeatures_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) (model.Group, error)) *MockService_SetGroupFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserOverrides provides a mock function with given fields: ctx, userID, overrides
func (_m *MockService) SetUserOverrides(ctx context.Context, userID uuid.UUID, overrides []model.FeatureOverrideView) error {
	ret := _m.Called(ctx, userID, overrides)

	if len(ret) == 0 {
		panic("no return value specified for SetUserOverrides")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []model.FeatureOverrideView) error); ok {
		r0 = rf(ctx, userID, overrides)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_SetUserOverrides_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserOverrides'
type MockService_SetUserOverrides_Call struct {
	*mock.Call
}

// SetUserOverrides is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - overrides []model.FeatureOverrideView
func (_e *MockService_Expecter) SetUserOverrides(ctx interface{}, userID interface{}, overrides interface{}) *MockService_SetUserOverrides_Call {
	return &MockService_SetUserOverrides_Call{Call: _e.mock.On("SetUserOverrides", ctx, userID, overrides)}
}

func (_c *MockService_SetUserOverrides_Call) Run(run func(ctx context.Context, userID uuid.UUID, overrides []model.FeatureOverrideView)) *MockService_SetUserOverrides_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]model.FeatureOverrideView))
	})
	return _c
}

func (_c *MockService_SetUserOverrides_Call) Return(_a0 error) *MockService_SetUserOverrides_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_SetUserOverrides_Call) RunAndReturn(run func(context.Context, uuid.UUID, []model.FeatureOverrideView) error) *MockService_SetUserOverrides_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function with given fields: ctx, id, name, description
func (_m *MockService) UpdateGroup(ctx context.Context, id uuid.UUID, name string, description string) (model.Group, error) {
	ret := _m.Called(ctx, id, name, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (model.Group, error)); ok {
		return rf(ctx, id, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) model.Group); ok {
		r0 = rf(ctx, id, name, description)
	} else {
		r0 = ret.Get(0).(model.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, id, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockService_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
//   - description string
func (_e *MockService_Expecter) UpdateGroup(ctx interface{}, id interface{}, name interface{}, description interface{}) *MockService_UpdateGroup_Call {
	return &MockService_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, id, name, description)}
}

func (_c *MockService_UpdateGroup_Call) Run(run func(ctx context.Context, id uuid.UUID, name string, description string)) *MockService_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_UpdateGroup_Call) Return(_a0 model.Group, _a1 error) *MockService_UpdateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (model.Group, error)) *MockService_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
