// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	repository "github.com/all-in-one/internal/authnz/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockStorage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Close() *MockStorage_Close_Call {
	return &MockStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorage_Close_Call) Run(run func()) *MockStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Close_Call) Return(_a0 error) *MockStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Close_Call) RunAndReturn(run func() error) *MockStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SessionRepo provides a mock function with no fields
func (_m *MockStorage) SessionRepo() repository.SessionRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SessionRepo")
	}

	var r0 repository.SessionRepository
	if rf, ok := ret.Get(0).(func() repository.SessionRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.SessionRepository)
		}
	}

	return r0
}

// MockStorage_SessionRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionRepo'
type MockStorage_SessionRepo_Call struct {
	*mock.Call
}

// SessionRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) SessionRepo() *MockStorage_SessionRepo_Call {
	return &MockStorage_SessionRepo_Call{Call: _e.mock.On("SessionRepo")}
}

func (_c *MockStorage_SessionRepo_Call) Run(run func()) *MockStorage_SessionRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_SessionRepo_Call) Return(_a0 repository.SessionRepository) *MockStorage_SessionRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_SessionRepo_Call) RunAndReturn(run func() repository.SessionRepository) *MockStorage_SessionRepo_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepo provides a mock function with no fields
func (_m *MockStorage) UserRepo() repository.UserRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepo")
	}

	var r0 repository.UserRepository
	if rf, ok := ret.Get(0).(func() repository.UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserRepository)
		}
	}

	return r0
}

// MockStorage_UserRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepo'
type MockStorage_UserRepo_Call struct {
	*mock.Call
}

// UserRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) UserRepo() *MockStorage_UserRepo_Call {
	return &MockStorage_UserRepo_Call{Call: _e.mock.On("UserRepo")}
}

func (_c *MockStorage_UserRepo_Call) Run(run func()) *MockStorage_UserRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_UserRepo_Call) Return(_a0 repository.UserRepository) *MockStorage_UserRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UserRepo_Call) RunAndReturn(run func() repository.UserRepository) *MockStorage_UserRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
