// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/authnz/model"
	mock "github.com/stretchr/testify/mock"

	query "github.com/all-in-one/internal/query"

	uuid "github.com/google/uuid"
)

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session, opts
func (_m *MockSessionRepository) Create(ctx context.Context, session model.Session, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, session)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Session, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, session, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session model.Session
//   - opts ...query.QueryOptions
func (_e *MockSessionRepository_Expecter) Create(ctx interface{}, session interface{}, opts ...interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, session}, opts...)...)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, session model.Session, opts ...query.QueryOptions)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(model.Session), variadicArgs...)
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(_a0 error) *MockSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(context.Context, model.Session, ...query.QueryOptions) error) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTrx provides a mock function with given fields: ctx
func (_m *MockSessionRepository) CreateTrx(ctx context.Context) (query.QueryOptions, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrx")
	}

	var r0 query.QueryOptions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (query.QueryOptions, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) query.QueryOptions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(query.QueryOptions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_CreateTrx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrx'
type MockSessionRepository_CreateTrx_Call struct {
	*mock.Call
}

// CreateTrx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionRepository_Expecter) CreateTrx(ctx interface{}) *MockSessionRepository_CreateTrx_Call {
	return &MockSessionRepository_CreateTrx_Call{Call: _e.mock.On("CreateTrx", ctx)}
}

func (_c *MockSessionRepository_CreateTrx_Call) Run(run func(ctx context.Context)) *MockSessionRepository_CreateTrx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSessionRepository_CreateTrx_Call) Return(_a0 query.QueryOptions, _a1 error) *MockSessionRepository_CreateTrx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_CreateTrx_Call) RunAndReturn(run func(context.Context) (query.QueryOptions, error)) *MockSessionRepository_CreateTrx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSessionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSessionRepository_Delete_Call {
	return &MockSessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSessionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionRepository_Delete_Call) Return(_a0 error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockSessionRepository) Get(ctx context.Context, id uuid.UUID) (*model.Session, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Session); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionRepository_Expecter) Get(ctx interface{}, id interface{}) *MockSessionRepository_Get_Call {
	return &MockSessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockSessionRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionRepository_Get_Call) Return(_a0 *model.Session, _a1 error) *MockSessionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Session, error)) *MockSessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
