// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAccessResolver is an autogenerated mock type for the AccessResolver type
type MockAccessResolver struct {
	mock.Mock
}

type MockAccessResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessResolver) EXPECT() *MockAccessResolver_Expecter {
	return &MockAccessResolver_Expecter{mock: &_m.Mock}
}

// EffectiveFeatures provides a mock function with given fields: ctx, userID
func (_m *MockAccessResolver) EffectiveFeatures(ctx context.Context, userID uuid.UUID) (bool, uuid.UUID, string, []string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for EffectiveFeatures")
	}

	var r0 bool
	var r1 uuid.UUID
	var r2 string
	var r3 []string
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, uuid.UUID, string, []string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r1 = rf(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) string); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID) []string); ok {
		r3 = rf(ctx, userID)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).([]string)
		}
	}

	if rf, ok := ret.Get(4).(func(context.Context, uuid.UUID) error); ok {
		r4 = rf(ctx, userID)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MockAccessResolver_EffectiveFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EffectiveFeatures'
type MockAccessResolver_EffectiveFeatures_Call struct {
	*mock.Call
}

// EffectiveFeatures is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAccessResolver_Expecter) EffectiveFeatures(ctx interface{}, userID interface{}) *MockAccessResolver_EffectiveFeatures_Call {
	return &MockAccessResolver_EffectiveFeatures_Call{Call: _e.mock.On("EffectiveFeatures", ctx, userID)}
}

func (_c *MockAccessResolver_EffectiveFeatures_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAccessResolver_EffectiveFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAccessResolver_EffectiveFeatures_Call) Return(isAdmin bool, groupID uuid.UUID, groupName string, featureKeys []string, err error) *MockAccessResolver_EffectiveFeatures_Call {
	_c.Call.Return(isAdmin, groupID, groupName, featureKeys, err)
	return _c
}

func (_c *MockAccessResolver_EffectiveFeatures_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, uuid.UUID, string, []string, error)) *MockAccessResolver_EffectiveFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessResolver creates a new instance of MockAccessResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessResolver {
	mock := &MockAccessResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
