// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/authnz/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTOTPRepository is an autogenerated mock type for the TOTPRepository type
type MockTOTPRepository struct {
	mock.Mock
}

type MockTOTPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTOTPRepository) EXPECT() *MockTOTPRepository_Expecter {
	return &MockTOTPRepository_Expecter{mock: &_m.Mock}
}

// CreateChallenge provides a mock function with given fields: ctx, challenge
func (_m *MockTOTPRepository) CreateChallenge(ctx context.Context, challenge model.TOTPChallenge) error {
	ret := _m.Called(ctx, challenge)

	if len(ret) == 0 {
		panic("no return value specified for CreateChallenge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TOTPChallenge) error); ok {
		r0 = rf(ctx, challenge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTOTPRepository_CreateChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChallenge'
type MockTOTPRepository_CreateChallenge_Call struct {
	*mock.Call
}

// CreateChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - challenge model.TOTPChallenge
func (_e *MockTOTPRepository_Expecter) CreateChallenge(ctx interface{}, challenge interface{}) *MockTOTPRepository_CreateChallenge_Call {
	return &MockTOTPRepository_CreateChallenge_Call{Call: _e.mock.On("CreateChallenge", ctx, challenge)}
}

func (_c *MockTOTPRepository_CreateChallenge_Call) Run(run func(ctx context.Context, challenge model.TOTPChallenge)) *MockTOTPRepository_CreateChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TOTPChallenge))
	})
	return _c
}

func (_c *MockTOTPRepository_CreateChallenge_Call) Return(_a0 error) *MockTOTPRepository_CreateChallenge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTOTPRepository_CreateChallenge_Call) RunAndReturn(run func(context.Context, model.TOTPChallenge) error) *MockTOTPRepository_CreateChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRecoveryCodes provides a mock function with given fields: ctx, codes
func (_m *MockTOTPRepository) CreateRecoveryCodes(ctx context.Context, codes []model.RecoveryCode) error {
	ret := _m.Called(ctx, codes)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecoveryCodes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.RecoveryCode) error); ok {
		r0 = rf(ctx, codes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTOTPRepository_CreateRecoveryCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecoveryCodes'
type MockTOTPRepository_CreateRecoveryCodes_Call struct {
	*mock.Call
}

// CreateRecoveryCodes is a helper method to define mock.On call
//   - ctx context.Context
//   - codes []model.RecoveryCode
func (_e *MockTOTPRepository_Expecter) CreateRecoveryCodes(ctx interface{}, codes interface{}) *MockTOTPRepository_CreateRecoveryCodes_Call {
	return &MockTOTPRepository_CreateRecoveryCodes_Call{Call: _e.mock.On("CreateRecoveryCodes", ctx, codes)}
}

func (_c *MockTOTPRepository_CreateRecoveryCodes_Call) Run(run func(ctx context.Context, codes []model.RecoveryCode)) *MockTOTPRepository_CreateRecoveryCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.RecoveryCode))
	})
	return _c
}

func (_c *MockTOTPRepository_CreateRecoveryCodes_Call) Return(_a0 error) *MockTOTPRepository_CreateRecoveryCodes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTOTPRepository_CreateRecoveryCodes_Call) RunAndReturn(run func(context.Context, []model.RecoveryCode) error) *MockTOTPRepository_CreateRecoveryCodes_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChallenge provides a mock function with given fields: ctx, id
func (_m *MockTOTPRepository) DeleteChallenge(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChallenge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTOTPRepository_DeleteChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChallenge'
type MockTOTPRepository_DeleteChallenge_Call struct {
	*mock.Call
}

// DeleteChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTOTPRepository_Expecter) DeleteChallenge(ctx interface{}, id interface{}) *MockTOTPRepository_DeleteChallenge_Call {
	return &MockTOTPRepository_DeleteChallenge_Call{Call: _e.mock.On("DeleteChallenge", ctx, id)}
}

func (_c *MockTOTPRepository_DeleteChallenge_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTOTPRepository_DeleteChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTOTPRepository_DeleteChallenge_Call) Return(_a0 error) *MockTOTPRepository_DeleteChallenge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTOTPRepository_DeleteChallenge_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTOTPRepository_DeleteChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredChallenges provides a mock function with given fields: ctx
func (_m *MockTOTPRepository) DeleteExpiredChallenges(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredChallenges")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTOTPRepository_DeleteExpiredChallenges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredChallenges'
type MockTOTPRepository_DeleteExpiredChallenges_Call struct {
	*mock.Call
}

// DeleteExpiredChallenges is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTOTPRepository_Expecter) DeleteExpiredChallenges(ctx interface{}) *MockTOTPRepository_DeleteExpiredChallenges_Call {
	return &MockTOTPRepository_DeleteExpiredChallenges_Call{Call: _e.mock.On("DeleteExpiredChallenges", ctx)}
}

func (_c *MockTOTPRepository_DeleteExpiredChallenges_Call) Run(run func(ctx context.Context)) *MockTOTPRepository_DeleteExpiredChallenges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTOTPRepository_DeleteExpiredChallenges_Call) Return(_a0 error) *MockTOTPRepository_DeleteExpiredChallenges_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTOTPRepository_DeleteExpiredChallenges_Call) RunAndReturn(run func(context.Context) error) *MockTOTPRepository_DeleteExpiredChallenges_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecoveryCodesByUserID provides a mock function with given fields: ctx, userID
func (_m *MockTOTPRepository) DeleteRecoveryCodesByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecoveryCodesByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTOTPRepository_DeleteRecoveryCodesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecoveryCodesByUserID'
type MockTOTPRepository_DeleteRecoveryCodesByUserID_Call struct {
	*mock.Call
}

// DeleteRecoveryCodesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTOTPRepository_Expecter) DeleteRecoveryCodesByUserID(ctx interface{}, userID interface{}) *MockTOTPRepository_DeleteRecoveryCodesByUserID_Call {
	return &MockTOTPRepository_DeleteRecoveryCodesByUserID_Call{Call: _e.mock.On("DeleteRecoveryCodesByUserID", ctx, userID)}
}

func (_c *MockTOTPRepository_DeleteRecoveryCodesByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTOTPRepository_DeleteRecoveryCodesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTOTPRepository_DeleteRecoveryCodesByUserID_Call) Return(_a0 error) *MockTOTPRepository_DeleteRecoveryCodesByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTOTPRepository_DeleteRecoveryCodesByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTOTPRepository_DeleteRecoveryCodesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChallenge provides a mock function with given fields: ctx, id
func (_m *MockTOTPRepository) GetChallenge(ctx context.Context, id uuid.UUID) (*model.TOTPChallenge, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChallenge")
	}

	var r0 *model.TOTPChallenge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.TOTPChallenge, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.TOTPChallenge); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TOTPChallenge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTOTPRepository_GetChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChallenge'
type MockTOTPRepository_GetChallenge_Call struct {
	*mock.Call
}

// GetChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTOTPRepository_Expecter) GetChallenge(ctx interface{}, id interface{}) *MockTOTPRepository_GetChallenge_Call {
	return &MockTOTPRepository_GetChallenge_Call{Call: _e.mock.On("GetChallenge", ctx, id)}
}

func (_c *MockTOTPRepository_GetChallenge_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTOTPRepository_GetChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTOTPRepository_GetChallenge_Call) Return(_a0 *model.TOTPChallenge, _a1 error) *MockTOTPRepository_GetChallenge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTOTPRepository_GetChallenge_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.TOTPChallenge, error)) *MockTOTPRepository_GetChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnusedRecoveryCodes provides a mock function with given fields: ctx, userID
func (_m *MockTOTPRepository) GetUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]model.RecoveryCode, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnusedRecoveryCodes")
	}

	var r0 []model.RecoveryCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.RecoveryCode, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.RecoveryCode); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RecoveryCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTOTPRepository_GetUnusedRecoveryCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnusedRecoveryCodes'
type MockTOTPRepository_GetUnusedRecoveryCodes_Call struct {
	*mock.Call
}

// GetUnusedRecoveryCodes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTOTPRepository_Expecter) GetUnusedRecoveryCodes(ctx interface{}, userID interface{}) *MockTOTPRepository_GetUnusedRecoveryCodes_Call {
	return &MockTOTPRepository_GetUnusedRecoveryCodes_Call{Call: _e.mock.On("GetUnusedRecoveryCodes", ctx, userID)}
}

func (_c *MockTOTPRepository_GetUnusedRecoveryCodes_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTOTPRepository_GetUnusedRecoveryCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTOTPRepository_GetUnusedRecoveryCodes_Call) Return(_a0 []model.RecoveryCode, _a1 error) *MockTOTPRepository_GetUnusedRecoveryCodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTOTPRepository_GetUnusedRecoveryCodes_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.RecoveryCode, error)) *MockTOTPRepository_GetUnusedRecoveryCodes_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementChallengeAttempts provides a mock function with given fields: ctx, id
func (_m *MockTOTPRepository) IncrementChallengeAttempts(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementChallengeAttempts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTOTPRepository_IncrementChallengeAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementChallengeAttempts'
type MockTOTPRepository_IncrementChallengeAttempts_Call struct {
	*mock.Call
}

// IncrementChallengeAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTOTPRepository_Expecter) IncrementChallengeAttempts(ctx interface{}, id interface{}) *MockTOTPRepository_IncrementChallengeAttempts_Call {
	return &MockTOTPRepository_IncrementChallengeAttempts_Call{Call: _e.mock.On("IncrementChallengeAttempts", ctx, id)}
}

func (_c *MockTOTPRepository_IncrementChallengeAttempts_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTOTPRepository_IncrementChallengeAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTOTPRepository_IncrementChallengeAttempts_Call) Return(_a0 error) *MockTOTPRepository_IncrementChallengeAttempts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTOTPRepository_IncrementChallengeAttempts_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTOTPRepository_IncrementChallengeAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRecoveryCodeUsed provides a mock function with given fields: ctx, id
func (_m *MockTOTPRepository) MarkRecoveryCodeUsed(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRecoveryCodeUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTOTPRepository_MarkRecoveryCodeUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRecoveryCodeUsed'
type MockTOTPRepository_MarkRecoveryCodeUsed_Call struct {
	*mock.Call
}

// MarkRecoveryCodeUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTOTPRepository_Expecter) MarkRecoveryCodeUsed(ctx interface{}, id interface{}) *MockTOTPRepository_MarkRecoveryCodeUsed_Call {
	return &MockTOTPRepository_MarkRecoveryCodeUsed_Call{Call: _e.mock.On("MarkRecoveryCodeUsed", ctx, id)}
}

func (_c *MockTOTPRepository_MarkRecoveryCodeUsed_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTOTPRepository_MarkRecoveryCodeUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTOTPRepository_MarkRecoveryCodeUsed_Call) Return(_a0 error) *MockTOTPRepository_MarkRecoveryCodeUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTOTPRepository_MarkRecoveryCodeUsed_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTOTPRepository_MarkRecoveryCodeUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTOTPRepository creates a new instance of MockTOTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTOTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTOTPRepository {
	mock := &MockTOTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
