// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shortener/v1/shortener.proto

package shortenerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortLink struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	TargetUrl      string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	OwnerId        *int64                 `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	IsActive       bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ClickCount     uint64                 `protobuf:"varint,8,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	LastAccessedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_accessed_at,json=lastAccessedAt,proto3,oneof" json:"last_accessed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShortLink) Reset() {
	*x = ShortLink{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLink) ProtoMessage() {}

func (x *ShortLink) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLink.ProtoReflect.Descriptor instead.
func (*ShortLink) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShortLink) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShortLink) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *ShortLink) GetOwnerId() int64 {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return 0
}

func (x *ShortLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShortLink) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ShortLink) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ShortLink) GetClickCount() uint64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *ShortLink) GetLastAccessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessedAt
	}
	return nil
}

type CreateShortLinkRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	// Reserved for M2 custom-slug feature; server returns 400 if set.
	CustomCode    *string `protobuf:"bytes,3,opt,name=custom_code,json=customCode,proto3,oneof" json:"custom_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkRequest) Reset() {
	*x = CreateShortLinkRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkRequest) ProtoMessage() {}

func (x *CreateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortLinkRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *CreateShortLinkRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateShortLinkRequest) GetCustomCode() string {
	if x != nil && x.CustomCode != nil {
		return *x.CustomCode
	}
	return ""
}

type CreateShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ShortLink             `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkResponse) Reset() {
	*x = CreateShortLinkResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkResponse) ProtoMessage() {}

func (x *CreateShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShortLinkResponse) GetLink() *ShortLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type ListShortLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortLinksRequest) Reset() {
	*x = ListShortLinksRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortLinksRequest) ProtoMessage() {}

func (x *ListShortLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortLinksRequest.ProtoReflect.Descriptor instead.
func (*ListShortLinksRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ListShortLinksRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListShortLinksRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListShortLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*ShortLink           `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShortLinksResponse) Reset() {
	*x = ListShortLinksResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShortLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShortLinksResponse) ProtoMessage() {}

func (x *ListShortLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShortLinksResponse.ProtoReflect.Descriptor instead.
func (*ListShortLinksResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ListShortLinksResponse) GetLinks() []*ShortLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListShortLinksResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinkRequest) Reset() {
	*x = GetShortLinkRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinkRequest) ProtoMessage() {}

func (x *GetShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinkRequest.ProtoReflect.Descriptor instead.
func (*GetShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetShortLinkRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ShortLink             `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortLinkResponse) Reset() {
	*x = GetShortLinkResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortLinkResponse) ProtoMessage() {}

func (x *GetShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortLinkResponse.ProtoReflect.Descriptor instead.
func (*GetShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *GetShortLinkResponse) GetLink() *ShortLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type UpdateShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	IsActive      *bool                  `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShortLinkRequest) Reset() {
	*x = UpdateShortLinkRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShortLinkRequest) ProtoMessage() {}

func (x *UpdateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShortLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateShortLinkRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateShortLinkRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateShortLinkRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type UpdateShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *ShortLink             `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShortLinkResponse) Reset() {
	*x = UpdateShortLinkResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShortLinkResponse) ProtoMessage() {}

func (x *UpdateShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShortLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateShortLinkResponse) GetLink() *ShortLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type DeleteShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortLinkRequest) Reset() {
	*x = DeleteShortLinkRequest{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortLinkRequest) ProtoMessage() {}

func (x *DeleteShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteShortLinkRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeleteShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortLinkResponse) Reset() {
	*x = DeleteShortLinkResponse{}
	mi := &file_shortener_v1_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortLinkResponse) ProtoMessage() {}

func (x *DeleteShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_v1_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_shortener_v1_shortener_proto_rawDescGZIP(), []int{10}
}

var File_shortener_v1_shortener_proto protoreflect.FileDescriptor

const file_shortener_v1_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1cshortener/v1/shortener.proto\x12\fshortener.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x03\n" +
	"\tShortLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12\x1e\n" +
	"\bowner_id\x18\x04 \x01(\x03H\x00R\aownerId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\texpiresAt\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1f\n" +
	"\vclick_count\x18\b \x01(\x04R\n" +
	"clickCount\x12I\n" +
	"\x10last_accessed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x0elastAccessedAt\x88\x01\x01B\v\n" +
	"\t_owner_idB\r\n" +
	"\v_expires_atB\x13\n" +
	"\x11_last_accessed_at\"\xbc\x01\n" +
	"\x16CreateShortLinkRequest\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\x12>\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01\x12$\n" +
	"\vcustom_code\x18\x03 \x01(\tH\x01R\n" +
	"customCode\x88\x01\x01B\r\n" +
	"\v_expires_atB\x0e\n" +
	"\f_custom_code\"F\n" +
	"\x17CreateShortLinkResponse\x12+\n" +
	"\x04link\x18\x01 \x01(\v2\x17.shortener.v1.ShortLinkR\x04link\"H\n" +
	"\x15ListShortLinksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"]\n" +
	"\x16ListShortLinksResponse\x12-\n" +
	"\x05links\x18\x01 \x03(\v2\x17.shortener.v1.ShortLinkR\x05links\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\")\n" +
	"\x13GetShortLinkRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"C\n" +
	"\x14GetShortLinkResponse\x12+\n" +
	"\x04link\x18\x01 \x01(\v2\x17.shortener.v1.ShortLinkR\x04link\"\xab\x01\n" +
	"\x16UpdateShortLinkRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\tis_active\x18\x02 \x01(\bH\x00R\bisActive\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\texpiresAt\x88\x01\x01B\f\n" +
	"\n" +
	"_is_activeB\r\n" +
	"\v_expires_at\"F\n" +
	"\x17UpdateShortLinkResponse\x12+\n" +
	"\x04link\x18\x01 \x01(\v2\x17.shortener.v1.ShortLinkR\x04link\",\n" +
	"\x16DeleteShortLinkRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x19\n" +
	"\x17DeleteShortLinkResponseB<Z:github.com/all-in-one/internal/shortener/pb/v1;shortenerv1b\x06proto3"

var (
	file_shortener_v1_shortener_proto_rawDescOnce sync.Once
	file_shortener_v1_shortener_proto_rawDescData []byte
)

func file_shortener_v1_shortener_proto_rawDescGZIP() []byte {
	file_shortener_v1_shortener_proto_rawDescOnce.Do(func() {
		file_shortener_v1_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_v1_shortener_proto_rawDesc), len(file_shortener_v1_shortener_proto_rawDesc)))
	})
	return file_shortener_v1_shortener_proto_rawDescData
}

var file_shortener_v1_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shortener_v1_shortener_proto_goTypes = []any{
	(*ShortLink)(nil),               // 0: shortener.v1.ShortLink
	(*CreateShortLinkRequest)(nil),  // 1: shortener.v1.CreateShortLinkRequest
	(*CreateShortLinkResponse)(nil), // 2: shortener.v1.CreateShortLinkResponse
	(*ListShortLinksRequest)(nil),   // 3: shortener.v1.ListShortLinksRequest
	(*ListShortLinksResponse)(nil),  // 4: shortener.v1.ListShortLinksResponse
	(*GetShortLinkRequest)(nil),     // 5: shortener.v1.GetShortLinkRequest
	(*GetShortLinkResponse)(nil),    // 6: shortener.v1.GetShortLinkResponse
	(*UpdateShortLinkRequest)(nil),  // 7: shortener.v1.UpdateShortLinkRequest
	(*UpdateShortLinkResponse)(nil), // 8: shortener.v1.UpdateShortLinkResponse
	(*DeleteShortLinkRequest)(nil),  // 9: shortener.v1.DeleteShortLinkRequest
	(*DeleteShortLinkResponse)(nil), // 10: shortener.v1.DeleteShortLinkResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_shortener_v1_shortener_proto_depIdxs = []int32{
	11, // 0: shortener.v1.ShortLink.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: shortener.v1.ShortLink.expires_at:type_name -> google.protobuf.Timestamp
	11, // 2: shortener.v1.ShortLink.last_accessed_at:type_name -> google.protobuf.Timestamp
	11, // 3: shortener.v1.CreateShortLinkRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: shortener.v1.CreateShortLinkResponse.link:type_name -> shortener.v1.ShortLink
	0,  // 5: shortener.v1.ListShortLinksResponse.links:type_name -> shortener.v1.ShortLink
	0,  // 6: shortener.v1.GetShortLinkResponse.link:type_name -> shortener.v1.ShortLink
	11, // 7: shortener.v1.UpdateShortLinkRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 8: shortener.v1.UpdateShortLinkResponse.link:type_name -> shortener.v1.ShortLink
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_shortener_v1_shortener_proto_init() }
func file_shortener_v1_shortener_proto_init() {
	if File_shortener_v1_shortener_proto != nil {
		return
	}
	file_shortener_v1_shortener_proto_msgTypes[0].OneofWrappers = []any{}
	file_shortener_v1_shortener_proto_msgTypes[1].OneofWrappers = []any{}
	file_shortener_v1_shortener_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_v1_shortener_proto_rawDesc), len(file_shortener_v1_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shortener_v1_shortener_proto_goTypes,
		DependencyIndexes: file_shortener_v1_shortener_proto_depIdxs,
		MessageInfos:      file_shortener_v1_shortener_proto_msgTypes,
	}.Build()
	File_shortener_v1_shortener_proto = out.File
	file_shortener_v1_shortener_proto_goTypes = nil
	file_shortener_v1_shortener_proto_depIdxs = nil
}
