// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file shortener/v1/shortener.proto (package shortener.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shortener/v1/shortener.proto.
 */
export const file_shortener_v1_shortener: GenFile = /*@__PURE__*/
  fileDesc("ChxzaG9ydGVuZXIvdjEvc2hvcnRlbmVyLnByb3RvEgxzaG9ydGVuZXIudjEiyQIKCVNob3J0TGluaxIKCgJpZBgBIAEoCRIMCgRjb2RlGAIgASgJEhIKCnRhcmdldF91cmwYAyABKAkSFQoIb3duZXJfaWQYBCABKAlIAIgBARIuCgpjcmVhdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIzCgpleHBpcmVzX2F0GAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgBiAEBEhEKCWlzX2FjdGl2ZRgHIAEoCBITCgtjbGlja19jb3VudBgIIAEoBBI5ChBsYXN0X2FjY2Vzc2VkX2F0GAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgCiAEBQgsKCV9vd25lcl9pZEINCgtfZXhwaXJlc19hdEITChFfbGFzdF9hY2Nlc3NlZF9hdCKaAQoWQ3JlYXRlU2hvcnRMaW5rUmVxdWVzdBISCgp0YXJnZXRfdXJsGAEgASgJEjMKCmV4cGlyZXNfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSACIAQESGAoLY3VzdG9tX2NvZGUYAyABKAlIAYgBAUINCgtfZXhwaXJlc19hdEIOCgxfY3VzdG9tX2NvZGUiQAoXQ3JlYXRlU2hvcnRMaW5rUmVzcG9uc2USJQoEbGluaxgBIAEoCzIXLnNob3J0ZW5lci52MS5TaG9ydExpbmsiOAoVTGlzdFNob3J0TGlua3NSZXF1ZXN0EgwKBHBhZ2UYASABKA0SEQoJcGFnZV9zaXplGAIgASgNIk8KFkxpc3RTaG9ydExpbmtzUmVzcG9uc2USJgoFbGlua3MYASADKAsyFy5zaG9ydGVuZXIudjEuU2hvcnRMaW5rEg0KBXRvdGFsGAIgASgNIiMKE0dldFNob3J0TGlua1JlcXVlc3QSDAoEY29kZRgBIAEoCSI9ChRHZXRTaG9ydExpbmtSZXNwb25zZRIlCgRsaW5rGAEgASgLMhcuc2hvcnRlbmVyLnYxLlNob3J0TGluayKQAQoWVXBkYXRlU2hvcnRMaW5rUmVxdWVzdBIMCgRjb2RlGAEgASgJEhYKCWlzX2FjdGl2ZRgCIAEoCEgAiAEBEjMKCmV4cGlyZXNfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAGIAQFCDAoKX2lzX2FjdGl2ZUINCgtfZXhwaXJlc19hdCJAChdVcGRhdGVTaG9ydExpbmtSZXNwb25zZRIlCgRsaW5rGAEgASgLMhcuc2hvcnRlbmVyLnYxLlNob3J0TGluayImChZEZWxldGVTaG9ydExpbmtSZXF1ZXN0EgwKBGNvZGUYASABKAkiGQoXRGVsZXRlU2hvcnRMaW5rUmVzcG9uc2VCPFo6Z2l0aHViLmNvbS9hbGwtaW4tb25lL2ludGVybmFsL3Nob3J0ZW5lci9wYi92MTtzaG9ydGVuZXJ2MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message shortener.v1.ShortLink
 */
export type ShortLink = Message<"shortener.v1.ShortLink"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: string target_url = 3;
   */
  targetUrl: string;

  /**
   * @generated from field: optional string owner_id = 4;
   */
  ownerId?: string | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: optional google.protobuf.Timestamp expires_at = 6;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * @generated from field: bool is_active = 7;
   */
  isActive: boolean;

  /**
   * @generated from field: uint64 click_count = 8;
   */
  clickCount: bigint;

  /**
   * @generated from field: optional google.protobuf.Timestamp last_accessed_at = 9;
   */
  lastAccessedAt?: Timestamp | undefined;
};

/**
 * Describes the message shortener.v1.ShortLink.
 * Use `create(ShortLinkSchema)` to create a new message.
 */
export const ShortLinkSchema: GenMessage<ShortLink> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 0);

/**
 * @generated from message shortener.v1.CreateShortLinkRequest
 */
export type CreateShortLinkRequest = Message<"shortener.v1.CreateShortLinkRequest"> & {
  /**
   * @generated from field: string target_url = 1;
   */
  targetUrl: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp | undefined;

  /**
   * Reserved for M2 custom-slug feature; server returns 400 if set.
   *
   * @generated from field: optional string custom_code = 3;
   */
  customCode?: string | undefined;
};

/**
 * Describes the message shortener.v1.CreateShortLinkRequest.
 * Use `create(CreateShortLinkRequestSchema)` to create a new message.
 */
export const CreateShortLinkRequestSchema: GenMessage<CreateShortLinkRequest> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 1);

/**
 * @generated from message shortener.v1.CreateShortLinkResponse
 */
export type CreateShortLinkResponse = Message<"shortener.v1.CreateShortLinkResponse"> & {
  /**
   * @generated from field: shortener.v1.ShortLink link = 1;
   */
  link?: ShortLink | undefined;
};

/**
 * Describes the message shortener.v1.CreateShortLinkResponse.
 * Use `create(CreateShortLinkResponseSchema)` to create a new message.
 */
export const CreateShortLinkResponseSchema: GenMessage<CreateShortLinkResponse> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 2);

/**
 * @generated from message shortener.v1.ListShortLinksRequest
 */
export type ListShortLinksRequest = Message<"shortener.v1.ListShortLinksRequest"> & {
  /**
   * @generated from field: uint32 page = 1;
   */
  page: number;

  /**
   * @generated from field: uint32 page_size = 2;
   */
  pageSize: number;
};

/**
 * Describes the message shortener.v1.ListShortLinksRequest.
 * Use `create(ListShortLinksRequestSchema)` to create a new message.
 */
export const ListShortLinksRequestSchema: GenMessage<ListShortLinksRequest> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 3);

/**
 * @generated from message shortener.v1.ListShortLinksResponse
 */
export type ListShortLinksResponse = Message<"shortener.v1.ListShortLinksResponse"> & {
  /**
   * @generated from field: repeated shortener.v1.ShortLink links = 1;
   */
  links: ShortLink[];

  /**
   * @generated from field: uint32 total = 2;
   */
  total: number;
};

/**
 * Describes the message shortener.v1.ListShortLinksResponse.
 * Use `create(ListShortLinksResponseSchema)` to create a new message.
 */
export const ListShortLinksResponseSchema: GenMessage<ListShortLinksResponse> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 4);

/**
 * @generated from message shortener.v1.GetShortLinkRequest
 */
export type GetShortLinkRequest = Message<"shortener.v1.GetShortLinkRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message shortener.v1.GetShortLinkRequest.
 * Use `create(GetShortLinkRequestSchema)` to create a new message.
 */
export const GetShortLinkRequestSchema: GenMessage<GetShortLinkRequest> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 5);

/**
 * @generated from message shortener.v1.GetShortLinkResponse
 */
export type GetShortLinkResponse = Message<"shortener.v1.GetShortLinkResponse"> & {
  /**
   * @generated from field: shortener.v1.ShortLink link = 1;
   */
  link?: ShortLink | undefined;
};

/**
 * Describes the message shortener.v1.GetShortLinkResponse.
 * Use `create(GetShortLinkResponseSchema)` to create a new message.
 */
export const GetShortLinkResponseSchema: GenMessage<GetShortLinkResponse> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 6);

/**
 * @generated from message shortener.v1.UpdateShortLinkRequest
 */
export type UpdateShortLinkRequest = Message<"shortener.v1.UpdateShortLinkRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: optional bool is_active = 2;
   */
  isActive?: boolean | undefined;

  /**
   * @generated from field: optional google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp | undefined;
};

/**
 * Describes the message shortener.v1.UpdateShortLinkRequest.
 * Use `create(UpdateShortLinkRequestSchema)` to create a new message.
 */
export const UpdateShortLinkRequestSchema: GenMessage<UpdateShortLinkRequest> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 7);

/**
 * @generated from message shortener.v1.UpdateShortLinkResponse
 */
export type UpdateShortLinkResponse = Message<"shortener.v1.UpdateShortLinkResponse"> & {
  /**
   * @generated from field: shortener.v1.ShortLink link = 1;
   */
  link?: ShortLink | undefined;
};

/**
 * Describes the message shortener.v1.UpdateShortLinkResponse.
 * Use `create(UpdateShortLinkResponseSchema)` to create a new message.
 */
export const UpdateShortLinkResponseSchema: GenMessage<UpdateShortLinkResponse> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 8);

/**
 * @generated from message shortener.v1.DeleteShortLinkRequest
 */
export type DeleteShortLinkRequest = Message<"shortener.v1.DeleteShortLinkRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message shortener.v1.DeleteShortLinkRequest.
 * Use `create(DeleteShortLinkRequestSchema)` to create a new message.
 */
export const DeleteShortLinkRequestSchema: GenMessage<DeleteShortLinkRequest> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 9);

/**
 * @generated from message shortener.v1.DeleteShortLinkResponse
 */
export type DeleteShortLinkResponse = Message<"shortener.v1.DeleteShortLinkResponse"> & {
};

/**
 * Describes the message shortener.v1.DeleteShortLinkResponse.
 * Use `create(DeleteShortLinkResponseSchema)` to create a new message.
 */
export const DeleteShortLinkResponseSchema: GenMessage<DeleteShortLinkResponse> = /*@__PURE__*/
  messageDesc(file_shortener_v1_shortener, 10);

