// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/shortener/model"
	mock "github.com/stretchr/testify/mock"
)

// MockShortLinkRepository is an autogenerated mock type for the ShortLinkRepository type
type MockShortLinkRepository struct {
	mock.Mock
}

type MockShortLinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortLinkRepository) EXPECT() *MockShortLinkRepository_Expecter {
	return &MockShortLinkRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, link, ownerID
func (_m *MockShortLinkRepository) Create(ctx context.Context, link model.ShortLink, ownerID string) (model.ShortLink, error) {
	ret := _m.Called(ctx, link, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.ShortLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShortLink, string) (model.ShortLink, error)); ok {
		return rf(ctx, link, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ShortLink, string) model.ShortLink); ok {
		r0 = rf(ctx, link, ownerID)
	} else {
		r0 = ret.Get(0).(model.ShortLink)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ShortLink, string) error); ok {
		r1 = rf(ctx, link, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShortLinkRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockShortLinkRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - link model.ShortLink
//   - ownerID string
func (_e *MockShortLinkRepository_Expecter) Create(ctx interface{}, link interface{}, ownerID interface{}) *MockShortLinkRepository_Create_Call {
	return &MockShortLinkRepository_Create_Call{Call: _e.mock.On("Create", ctx, link, ownerID)}
}

func (_c *MockShortLinkRepository_Create_Call) Run(run func(ctx context.Context, link model.ShortLink, ownerID string)) *MockShortLinkRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShortLink), args[2].(string))
	})
	return _c
}

func (_c *MockShortLinkRepository_Create_Call) Return(_a0 model.ShortLink, _a1 error) *MockShortLinkRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShortLinkRepository_Create_Call) RunAndReturn(run func(context.Context, model.ShortLink, string) (model.ShortLink, error)) *MockShortLinkRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, code, ownerID
func (_m *MockShortLinkRepository) Delete(ctx context.Context, code string, ownerID string) error {
	ret := _m.Called(ctx, code, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, code, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShortLinkRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockShortLinkRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - ownerID string
func (_e *MockShortLinkRepository_Expecter) Delete(ctx interface{}, code interface{}, ownerID interface{}) *MockShortLinkRepository_Delete_Call {
	return &MockShortLinkRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, code, ownerID)}
}

func (_c *MockShortLinkRepository_Delete_Call) Run(run func(ctx context.Context, code string, ownerID string)) *MockShortLinkRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockShortLinkRepository_Delete_Call) Return(_a0 error) *MockShortLinkRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShortLinkRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockShortLinkRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *MockShortLinkRepository) GetByCode(ctx context.Context, code string) (model.ShortLink, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 model.ShortLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.ShortLink, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.ShortLink); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(model.ShortLink)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShortLinkRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockShortLinkRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockShortLinkRepository_Expecter) GetByCode(ctx interface{}, code interface{}) *MockShortLinkRepository_GetByCode_Call {
	return &MockShortLinkRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *MockShortLinkRepository_GetByCode_Call) Run(run func(ctx context.Context, code string)) *MockShortLinkRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockShortLinkRepository_GetByCode_Call) Return(_a0 model.ShortLink, _a1 error) *MockShortLinkRepository_GetByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShortLinkRepository_GetByCode_Call) RunAndReturn(run func(context.Context, string) (model.ShortLink, error)) *MockShortLinkRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCodeOwned provides a mock function with given fields: ctx, code, ownerID
func (_m *MockShortLinkRepository) GetByCodeOwned(ctx context.Context, code string, ownerID string) (model.ShortLink, error) {
	ret := _m.Called(ctx, code, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCodeOwned")
	}

	var r0 model.ShortLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.ShortLink, error)); ok {
		return rf(ctx, code, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.ShortLink); ok {
		r0 = rf(ctx, code, ownerID)
	} else {
		r0 = ret.Get(0).(model.ShortLink)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShortLinkRepository_GetByCodeOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCodeOwned'
type MockShortLinkRepository_GetByCodeOwned_Call struct {
	*mock.Call
}

// GetByCodeOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - ownerID string
func (_e *MockShortLinkRepository_Expecter) GetByCodeOwned(ctx interface{}, code interface{}, ownerID interface{}) *MockShortLinkRepository_GetByCodeOwned_Call {
	return &MockShortLinkRepository_GetByCodeOwned_Call{Call: _e.mock.On("GetByCodeOwned", ctx, code, ownerID)}
}

func (_c *MockShortLinkRepository_GetByCodeOwned_Call) Run(run func(ctx context.Context, code string, ownerID string)) *MockShortLinkRepository_GetByCodeOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockShortLinkRepository_GetByCodeOwned_Call) Return(_a0 model.ShortLink, _a1 error) *MockShortLinkRepository_GetByCodeOwned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShortLinkRepository_GetByCodeOwned_Call) RunAndReturn(run func(context.Context, string, string) (model.ShortLink, error)) *MockShortLinkRepository_GetByCodeOwned_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementClick provides a mock function with given fields: ctx, code, now
func (_m *MockShortLinkRepository) IncrementClick(ctx context.Context, code string, now string) error {
	ret := _m.Called(ctx, code, now)

	if len(ret) == 0 {
		panic("no return value specified for IncrementClick")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, code, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShortLinkRepository_IncrementClick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementClick'
type MockShortLinkRepository_IncrementClick_Call struct {
	*mock.Call
}

// IncrementClick is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - now string
func (_e *MockShortLinkRepository_Expecter) IncrementClick(ctx interface{}, code interface{}, now interface{}) *MockShortLinkRepository_IncrementClick_Call {
	return &MockShortLinkRepository_IncrementClick_Call{Call: _e.mock.On("IncrementClick", ctx, code, now)}
}

func (_c *MockShortLinkRepository_IncrementClick_Call) Run(run func(ctx context.Context, code string, now string)) *MockShortLinkRepository_IncrementClick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockShortLinkRepository_IncrementClick_Call) Return(_a0 error) *MockShortLinkRepository_IncrementClick_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShortLinkRepository_IncrementClick_Call) RunAndReturn(run func(context.Context, string, string) error) *MockShortLinkRepository_IncrementClick_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOwner provides a mock function with given fields: ctx, ownerID, page, pageSize
func (_m *MockShortLinkRepository) ListByOwner(ctx context.Context, ownerID string, page uint32, pageSize uint32) ([]model.ShortLink, uint32, error) {
	ret := _m.Called(ctx, ownerID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwner")
	}

	var r0 []model.ShortLink
	var r1 uint32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32, uint32) ([]model.ShortLink, uint32, error)); ok {
		return rf(ctx, ownerID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint32, uint32) []model.ShortLink); ok {
		r0 = rf(ctx, ownerID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShortLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint32, uint32) uint32); ok {
		r1 = rf(ctx, ownerID, page, pageSize)
	} else {
		r1 = ret.Get(1).(uint32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, uint32, uint32) error); ok {
		r2 = rf(ctx, ownerID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockShortLinkRepository_ListByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwner'
type MockShortLinkRepository_ListByOwner_Call struct {
	*mock.Call
}

// ListByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - page uint32
//   - pageSize uint32
func (_e *MockShortLinkRepository_Expecter) ListByOwner(ctx interface{}, ownerID interface{}, page interface{}, pageSize interface{}) *MockShortLinkRepository_ListByOwner_Call {
	return &MockShortLinkRepository_ListByOwner_Call{Call: _e.mock.On("ListByOwner", ctx, ownerID, page, pageSize)}
}

func (_c *MockShortLinkRepository_ListByOwner_Call) Run(run func(ctx context.Context, ownerID string, page uint32, pageSize uint32)) *MockShortLinkRepository_ListByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint32), args[3].(uint32))
	})
	return _c
}

func (_c *MockShortLinkRepository_ListByOwner_Call) Return(_a0 []model.ShortLink, _a1 uint32, _a2 error) *MockShortLinkRepository_ListByOwner_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockShortLinkRepository_ListByOwner_Call) RunAndReturn(run func(context.Context, string, uint32, uint32) ([]model.ShortLink, uint32, error)) *MockShortLinkRepository_ListByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, link, ownerID
func (_m *MockShortLinkRepository) Update(ctx context.Context, link model.ShortLink, ownerID string) (model.ShortLink, error) {
	ret := _m.Called(ctx, link, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.ShortLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShortLink, string) (model.ShortLink, error)); ok {
		return rf(ctx, link, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ShortLink, string) model.ShortLink); ok {
		r0 = rf(ctx, link, ownerID)
	} else {
		r0 = ret.Get(0).(model.ShortLink)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ShortLink, string) error); ok {
		r1 = rf(ctx, link, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShortLinkRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockShortLinkRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - link model.ShortLink
//   - ownerID string
func (_e *MockShortLinkRepository_Expecter) Update(ctx interface{}, link interface{}, ownerID interface{}) *MockShortLinkRepository_Update_Call {
	return &MockShortLinkRepository_Update_Call{Call: _e.mock.On("Update", ctx, link, ownerID)}
}

func (_c *MockShortLinkRepository_Update_Call) Run(run func(ctx context.Context, link model.ShortLink, ownerID string)) *MockShortLinkRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShortLink), args[2].(string))
	})
	return _c
}

func (_c *MockShortLinkRepository_Update_Call) Return(_a0 model.ShortLink, _a1 error) *MockShortLinkRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShortLinkRepository_Update_Call) RunAndReturn(run func(context.Context, model.ShortLink, string) (model.ShortLink, error)) *MockShortLinkRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShortLinkRepository creates a new instance of MockShortLinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortLinkRepository {
	mock := &MockShortLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
