// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/all-in-one/internal/query"
	model "github.com/all-in-one/internal/ratelimit/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t, opts
func (_m *MockTokenRepository) Create(ctx context.Context, t model.AppToken, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, t)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AppToken, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, t, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t model.AppToken
//   - opts ...query.QueryOptions
func (_e *MockTokenRepository_Expecter) Create(ctx interface{}, t interface{}, opts ...interface{}) *MockTokenRepository_Create_Call {
	return &MockTokenRepository_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, t}, opts...)...)}
}

func (_c *MockTokenRepository_Create_Call) Run(run func(ctx context.Context, t model.AppToken, opts ...query.QueryOptions)) *MockTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(model.AppToken), variadicArgs...)
	})
	return _c
}

func (_c *MockTokenRepository_Create_Call) Return(_a0 error) *MockTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_Create_Call) RunAndReturn(run func(context.Context, model.AppToken, ...query.QueryOptions) error) *MockTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepository) GetByHash(ctx context.Context, tokenHash string) (model.AppToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 model.AppToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.AppToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.AppToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(model.AppToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockTokenRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) GetByHash(ctx interface{}, tokenHash interface{}) *MockTokenRepository_GetByHash_Call {
	return &MockTokenRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_GetByHash_Call) Return(_a0 model.AppToken, _a1 error) *MockTokenRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (model.AppToken, error)) *MockTokenRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockTokenRepository) List(ctx context.Context) ([]model.AppToken, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.AppToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.AppToken, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.AppToken); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AppToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTokenRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTokenRepository_Expecter) List(ctx interface{}) *MockTokenRepository_List_Call {
	return &MockTokenRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTokenRepository_List_Call) Run(run func(ctx context.Context)) *MockTokenRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTokenRepository_List_Call) Return(_a0 []model.AppToken, _a1 error) *MockTokenRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_List_Call) RunAndReturn(run func(context.Context) ([]model.AppToken, error)) *MockTokenRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id, opts
func (_m *MockTokenRepository) Revoke(ctx context.Context, id string, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts ...query.QueryOptions
func (_e *MockTokenRepository_Expecter) Revoke(ctx interface{}, id interface{}, opts ...interface{}) *MockTokenRepository_Revoke_Call {
	return &MockTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *MockTokenRepository_Revoke_Call) Run(run func(ctx context.Context, id string, opts ...query.QueryOptions)) *MockTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) Return(_a0 error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) RunAndReturn(run func(context.Context, string, ...query.QueryOptions) error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// TouchLastUsed provides a mock function with given fields: ctx, id, at
func (_m *MockTokenRepository) TouchLastUsed(ctx context.Context, id string, at time.Time) error {
	ret := _m.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for TouchLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_TouchLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchLastUsed'
type MockTokenRepository_TouchLastUsed_Call struct {
	*mock.Call
}

// TouchLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - at time.Time
func (_e *MockTokenRepository_Expecter) TouchLastUsed(ctx interface{}, id interface{}, at interface{}) *MockTokenRepository_TouchLastUsed_Call {
	return &MockTokenRepository_TouchLastUsed_Call{Call: _e.mock.On("TouchLastUsed", ctx, id, at)}
}

func (_c *MockTokenRepository_TouchLastUsed_Call) Run(run func(ctx context.Context, id string, at time.Time)) *MockTokenRepository_TouchLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockTokenRepository_TouchLastUsed_Call) Return(_a0 error) *MockTokenRepository_TouchLastUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_TouchLastUsed_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockTokenRepository_TouchLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
