// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/all-in-one/internal/query"
	model "github.com/all-in-one/internal/ratelimit/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRuleRepository is an autogenerated mock type for the RuleRepository type
type MockRuleRepository struct {
	mock.Mock
}

type MockRuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuleRepository) EXPECT() *MockRuleRepository_Expecter {
	return &MockRuleRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, targetKey
func (_m *MockRuleRepository) Get(ctx context.Context, targetKey string) (model.Rule, error) {
	ret := _m.Called(ctx, targetKey)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Rule, error)); ok {
		return rf(ctx, targetKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Rule); ok {
		r0 = rf(ctx, targetKey)
	} else {
		r0 = ret.Get(0).(model.Rule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, targetKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRuleRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRuleRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - targetKey string
func (_e *MockRuleRepository_Expecter) Get(ctx interface{}, targetKey interface{}) *MockRuleRepository_Get_Call {
	return &MockRuleRepository_Get_Call{Call: _e.mock.On("Get", ctx, targetKey)}
}

func (_c *MockRuleRepository_Get_Call) Run(run func(ctx context.Context, targetKey string)) *MockRuleRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRuleRepository_Get_Call) Return(_a0 model.Rule, _a1 error) *MockRuleRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRuleRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.Rule, error)) *MockRuleRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockRuleRepository) List(ctx context.Context) ([]model.Rule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Rule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Rule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRuleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRuleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRuleRepository_Expecter) List(ctx interface{}) *MockRuleRepository_List_Call {
	return &MockRuleRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRuleRepository_List_Call) Run(run func(ctx context.Context)) *MockRuleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRuleRepository_List_Call) Return(_a0 []model.Rule, _a1 error) *MockRuleRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRuleRepository_List_Call) RunAndReturn(run func(context.Context) ([]model.Rule, error)) *MockRuleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ResetToDefault provides a mock function with given fields: ctx, rule, opts
func (_m *MockRuleRepository) ResetToDefault(ctx context.Context, rule model.Rule, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, rule)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ResetToDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Rule, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, rule, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRuleRepository_ResetToDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetToDefault'
type MockRuleRepository_ResetToDefault_Call struct {
	*mock.Call
}

// ResetToDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - rule model.Rule
//   - opts ...query.QueryOptions
func (_e *MockRuleRepository_Expecter) ResetToDefault(ctx interface{}, rule interface{}, opts ...interface{}) *MockRuleRepository_ResetToDefault_Call {
	return &MockRuleRepository_ResetToDefault_Call{Call: _e.mock.On("ResetToDefault",
		append([]interface{}{ctx, rule}, opts...)...)}
}

func (_c *MockRuleRepository_ResetToDefault_Call) Run(run func(ctx context.Context, rule model.Rule, opts ...query.QueryOptions)) *MockRuleRepository_ResetToDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(model.Rule), variadicArgs...)
	})
	return _c
}

func (_c *MockRuleRepository_ResetToDefault_Call) Return(_a0 error) *MockRuleRepository_ResetToDefault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRuleRepository_ResetToDefault_Call) RunAndReturn(run func(context.Context, model.Rule, ...query.QueryOptions) error) *MockRuleRepository_ResetToDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Seed provides a mock function with given fields: ctx, rule, opts
func (_m *MockRuleRepository) Seed(ctx context.Context, rule model.Rule, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, rule)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Seed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Rule, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, rule, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRuleRepository_Seed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seed'
type MockRuleRepository_Seed_Call struct {
	*mock.Call
}

// Seed is a helper method to define mock.On call
//   - ctx context.Context
//   - rule model.Rule
//   - opts ...query.QueryOptions
func (_e *MockRuleRepository_Expecter) Seed(ctx interface{}, rule interface{}, opts ...interface{}) *MockRuleRepository_Seed_Call {
	return &MockRuleRepository_Seed_Call{Call: _e.mock.On("Seed",
		append([]interface{}{ctx, rule}, opts...)...)}
}

func (_c *MockRuleRepository_Seed_Call) Run(run func(ctx context.Context, rule model.Rule, opts ...query.QueryOptions)) *MockRuleRepository_Seed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(model.Rule), variadicArgs...)
	})
	return _c
}

func (_c *MockRuleRepository_Seed_Call) Return(_a0 error) *MockRuleRepository_Seed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRuleRepository_Seed_Call) RunAndReturn(run func(context.Context, model.Rule, ...query.QueryOptions) error) *MockRuleRepository_Seed_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, rule, opts
func (_m *MockRuleRepository) Update(ctx context.Context, rule model.Rule, opts ...query.QueryOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, rule)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Rule, ...query.QueryOptions) error); ok {
		r0 = rf(ctx, rule, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRuleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRuleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rule model.Rule
//   - opts ...query.QueryOptions
func (_e *MockRuleRepository_Expecter) Update(ctx interface{}, rule interface{}, opts ...interface{}) *MockRuleRepository_Update_Call {
	return &MockRuleRepository_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, rule}, opts...)...)}
}

func (_c *MockRuleRepository_Update_Call) Run(run func(ctx context.Context, rule model.Rule, opts ...query.QueryOptions)) *MockRuleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]query.QueryOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(query.QueryOptions)
			}
		}
		run(args[0].(context.Context), args[1].(model.Rule), variadicArgs...)
	})
	return _c
}

func (_c *MockRuleRepository_Update_Call) Return(_a0 error) *MockRuleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRuleRepository_Update_Call) RunAndReturn(run func(context.Context, model.Rule, ...query.QueryOptions) error) *MockRuleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuleRepository creates a new instance of MockRuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuleRepository {
	mock := &MockRuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
