// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCounterRepository is an autogenerated mock type for the CounterRepository type
type MockCounterRepository struct {
	mock.Mock
}

type MockCounterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCounterRepository) EXPECT() *MockCounterRepository_Expecter {
	return &MockCounterRepository_Expecter{mock: &_m.Mock}
}

// DeleteForTargetDay provides a mock function with given fields: ctx, targetKey, day
func (_m *MockCounterRepository) DeleteForTargetDay(ctx context.Context, targetKey string, day string) error {
	ret := _m.Called(ctx, targetKey, day)

	if len(ret) == 0 {
		panic("no return value specified for DeleteForTargetDay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, targetKey, day)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCounterRepository_DeleteForTargetDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteForTargetDay'
type MockCounterRepository_DeleteForTargetDay_Call struct {
	*mock.Call
}

// DeleteForTargetDay is a helper method to define mock.On call
//   - ctx context.Context
//   - targetKey string
//   - day string
func (_e *MockCounterRepository_Expecter) DeleteForTargetDay(ctx interface{}, targetKey interface{}, day interface{}) *MockCounterRepository_DeleteForTargetDay_Call {
	return &MockCounterRepository_DeleteForTargetDay_Call{Call: _e.mock.On("DeleteForTargetDay", ctx, targetKey, day)}
}

func (_c *MockCounterRepository_DeleteForTargetDay_Call) Run(run func(ctx context.Context, targetKey string, day string)) *MockCounterRepository_DeleteForTargetDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCounterRepository_DeleteForTargetDay_Call) Return(_a0 error) *MockCounterRepository_DeleteForTargetDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCounterRepository_DeleteForTargetDay_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCounterRepository_DeleteForTargetDay_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function with given fields: ctx, day
func (_m *MockCounterRepository) DeleteOlderThan(ctx context.Context, day string) (int64, error) {
	ret := _m.Called(ctx, day)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, day)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, day)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCounterRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockCounterRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - day string
func (_e *MockCounterRepository_Expecter) DeleteOlderThan(ctx interface{}, day interface{}) *MockCounterRepository_DeleteOlderThan_Call {
	return &MockCounterRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, day)}
}

func (_c *MockCounterRepository_DeleteOlderThan_Call) Run(run func(ctx context.Context, day string)) *MockCounterRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCounterRepository_DeleteOlderThan_Call) Return(_a0 int64, _a1 error) *MockCounterRepository_DeleteOlderThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCounterRepository_DeleteOlderThan_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockCounterRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// IncrAndGet provides a mock function with given fields: ctx, targetKey, bucketKey, day
func (_m *MockCounterRepository) IncrAndGet(ctx context.Context, targetKey string, bucketKey string, day string) (int, error) {
	ret := _m.Called(ctx, targetKey, bucketKey, day)

	if len(ret) == 0 {
		panic("no return value specified for IncrAndGet")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (int, error)); ok {
		return rf(ctx, targetKey, bucketKey, day)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int); ok {
		r0 = rf(ctx, targetKey, bucketKey, day)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, targetKey, bucketKey, day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCounterRepository_IncrAndGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrAndGet'
type MockCounterRepository_IncrAndGet_Call struct {
	*mock.Call
}

// IncrAndGet is a helper method to define mock.On call
//   - ctx context.Context
//   - targetKey string
//   - bucketKey string
//   - day string
func (_e *MockCounterRepository_Expecter) IncrAndGet(ctx interface{}, targetKey interface{}, bucketKey interface{}, day interface{}) *MockCounterRepository_IncrAndGet_Call {
	return &MockCounterRepository_IncrAndGet_Call{Call: _e.mock.On("IncrAndGet", ctx, targetKey, bucketKey, day)}
}

func (_c *MockCounterRepository_IncrAndGet_Call) Run(run func(ctx context.Context, targetKey string, bucketKey string, day string)) *MockCounterRepository_IncrAndGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCounterRepository_IncrAndGet_Call) Return(_a0 int, _a1 error) *MockCounterRepository_IncrAndGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCounterRepository_IncrAndGet_Call) RunAndReturn(run func(context.Context, string, string, string) (int, error)) *MockCounterRepository_IncrAndGet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCounterRepository creates a new instance of MockCounterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCounterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCounterRepository {
	mock := &MockCounterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
