// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/all-in-one/internal/query"
	repository "github.com/all-in-one/internal/ratelimit/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockStorage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Close() *MockStorage_Close_Call {
	return &MockStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorage_Close_Call) Run(run func()) *MockStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Close_Call) Return(_a0 error) *MockStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Close_Call) RunAndReturn(run func() error) *MockStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CounterRepo provides a mock function with no fields
func (_m *MockStorage) CounterRepo() repository.CounterRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CounterRepo")
	}

	var r0 repository.CounterRepository
	if rf, ok := ret.Get(0).(func() repository.CounterRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CounterRepository)
		}
	}

	return r0
}

// MockStorage_CounterRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CounterRepo'
type MockStorage_CounterRepo_Call struct {
	*mock.Call
}

// CounterRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) CounterRepo() *MockStorage_CounterRepo_Call {
	return &MockStorage_CounterRepo_Call{Call: _e.mock.On("CounterRepo")}
}

func (_c *MockStorage_CounterRepo_Call) Run(run func()) *MockStorage_CounterRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_CounterRepo_Call) Return(_a0 repository.CounterRepository) *MockStorage_CounterRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CounterRepo_Call) RunAndReturn(run func() repository.CounterRepository) *MockStorage_CounterRepo_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTrx provides a mock function with given fields: ctx
func (_m *MockStorage) CreateTrx(ctx context.Context) (query.QueryOptions, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrx")
	}

	var r0 query.QueryOptions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (query.QueryOptions, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) query.QueryOptions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(query.QueryOptions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateTrx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrx'
type MockStorage_CreateTrx_Call struct {
	*mock.Call
}

// CreateTrx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) CreateTrx(ctx interface{}) *MockStorage_CreateTrx_Call {
	return &MockStorage_CreateTrx_Call{Call: _e.mock.On("CreateTrx", ctx)}
}

func (_c *MockStorage_CreateTrx_Call) Run(run func(ctx context.Context)) *MockStorage_CreateTrx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_CreateTrx_Call) Return(_a0 query.QueryOptions, _a1 error) *MockStorage_CreateTrx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateTrx_Call) RunAndReturn(run func(context.Context) (query.QueryOptions, error)) *MockStorage_CreateTrx_Call {
	_c.Call.Return(run)
	return _c
}

// RuleRepo provides a mock function with no fields
func (_m *MockStorage) RuleRepo() repository.RuleRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RuleRepo")
	}

	var r0 repository.RuleRepository
	if rf, ok := ret.Get(0).(func() repository.RuleRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.RuleRepository)
		}
	}

	return r0
}

// MockStorage_RuleRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RuleRepo'
type MockStorage_RuleRepo_Call struct {
	*mock.Call
}

// RuleRepo is a helper method to define mock.On call
func (_e *MockStorage_Expecter) RuleRepo() *MockStorage_RuleRepo_Call {
	return &MockStorage_RuleRepo_Call{Call: _e.mock.On("RuleRepo")}
}

func (_c *MockStorage_RuleRepo_Call) Run(run func()) *MockStorage_RuleRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_RuleRepo_Call) Return(_a0 repository.RuleRepository) *MockStorage_RuleRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_RuleRepo_Call) RunAndReturn(run func() repository.RuleRepository) *MockStorage_RuleRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
