// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/oidc/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AuthRequestInfo provides a mock function with given fields: ctx, id
func (_m *MockService) AuthRequestInfo(ctx context.Context, id string) (model.AuthRequestInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthRequestInfo")
	}

	var r0 model.AuthRequestInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.AuthRequestInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.AuthRequestInfo); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.AuthRequestInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_AuthRequestInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthRequestInfo'
type MockService_AuthRequestInfo_Call struct {
	*mock.Call
}

// AuthRequestInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) AuthRequestInfo(ctx interface{}, id interface{}) *MockService_AuthRequestInfo_Call {
	return &MockService_AuthRequestInfo_Call{Call: _e.mock.On("AuthRequestInfo", ctx, id)}
}

func (_c *MockService_AuthRequestInfo_Call) Run(run func(ctx context.Context, id string)) *MockService_AuthRequestInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_AuthRequestInfo_Call) Return(_a0 model.AuthRequestInfo, _a1 error) *MockService_AuthRequestInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_AuthRequestInfo_Call) RunAndReturn(run func(context.Context, string) (model.AuthRequestInfo, error)) *MockService_AuthRequestInfo_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteAuthRequest provides a mock function with given fields: ctx, id, userID, browserID
func (_m *MockService) CompleteAuthRequest(ctx context.Context, id string, userID string, browserID string) (string, error) {
	ret := _m.Called(ctx, id, userID, browserID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteAuthRequest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, id, userID, browserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, id, userID, browserID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, id, userID, browserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CompleteAuthRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteAuthRequest'
type MockService_CompleteAuthRequest_Call struct {
	*mock.Call
}

// CompleteAuthRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - browserID string
func (_e *MockService_Expecter) CompleteAuthRequest(ctx interface{}, id interface{}, userID interface{}, browserID interface{}) *MockService_CompleteAuthRequest_Call {
	return &MockService_CompleteAuthRequest_Call{Call: _e.mock.On("CompleteAuthRequest", ctx, id, userID, browserID)}
}

func (_c *MockService_CompleteAuthRequest_Call) Run(run func(ctx context.Context, id string, userID string, browserID string)) *MockService_CompleteAuthRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_CompleteAuthRequest_Call) Return(_a0 string, _a1 error) *MockService_CompleteAuthRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CompleteAuthRequest_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *MockService_CompleteAuthRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClient provides a mock function with given fields: ctx, in, createdBy
func (_m *MockService) CreateClient(ctx context.Context, in model.CreateClientInput, createdBy string) (model.Client, string, error) {
	ret := _m.Called(ctx, in, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 model.Client
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateClientInput, string) (model.Client, string, error)); ok {
		return rf(ctx, in, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateClientInput, string) model.Client); ok {
		r0 = rf(ctx, in, createdBy)
	} else {
		r0 = ret.Get(0).(model.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateClientInput, string) string); ok {
		r1 = rf(ctx, in, createdBy)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.CreateClientInput, string) error); ok {
		r2 = rf(ctx, in, createdBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_CreateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClient'
type MockService_CreateClient_Call struct {
	*mock.Call
}

// CreateClient is a helper method to define mock.On call
//   - ctx context.Context
//   - in model.CreateClientInput
//   - createdBy string
func (_e *MockService_Expecter) CreateClient(ctx interface{}, in interface{}, createdBy interface{}) *MockService_CreateClient_Call {
	return &MockService_CreateClient_Call{Call: _e.mock.On("CreateClient", ctx, in, createdBy)}
}

func (_c *MockService_CreateClient_Call) Run(run func(ctx context.Context, in model.CreateClientInput, createdBy string)) *MockService_CreateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateClientInput), args[2].(string))
	})
	return _c
}

func (_c *MockService_CreateClient_Call) Return(_a0 model.Client, _a1 string, _a2 error) *MockService_CreateClient_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_CreateClient_Call) RunAndReturn(run func(context.Context, model.CreateClientInput, string) (model.Client, string, error)) *MockService_CreateClient_Call {
	_c.Call.Return(run)
	return _c
}

// ListClients provides a mock function with given fields: ctx
func (_m *MockService) ListClients(ctx context.Context) ([]model.Client, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []model.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Client, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Client); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClients'
type MockService_ListClients_Call struct {
	*mock.Call
}

// ListClients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListClients(ctx interface{}) *MockService_ListClients_Call {
	return &MockService_ListClients_Call{Call: _e.mock.On("ListClients", ctx)}
}

func (_c *MockService_ListClients_Call) Run(run func(ctx context.Context)) *MockService_ListClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListClients_Call) Return(_a0 []model.Client, _a1 error) *MockService_ListClients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListClients_Call) RunAndReturn(run func(context.Context) ([]model.Client, error)) *MockService_ListClients_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeClient provides a mock function with given fields: ctx, id
func (_m *MockService) RevokeClient(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_RevokeClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeClient'
type MockService_RevokeClient_Call struct {
	*mock.Call
}

// RevokeClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) RevokeClient(ctx interface{}, id interface{}) *MockService_RevokeClient_Call {
	return &MockService_RevokeClient_Call{Call: _e.mock.On("RevokeClient", ctx, id)}
}

func (_c *MockService_RevokeClient_Call) Run(run func(ctx context.Context, id string)) *MockService_RevokeClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_RevokeClient_Call) Return(_a0 error) *MockService_RevokeClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_RevokeClient_Call) RunAndReturn(run func(context.Context, string) error) *MockService_RevokeClient_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClient provides a mock function with given fields: ctx, id, in
func (_m *MockService) UpdateClient(ctx context.Context, id string, in model.UpdateClientInput) (model.Client, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClient")
	}

	var r0 model.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateClientInput) (model.Client, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateClientInput) model.Client); ok {
		r0 = rf(ctx, id, in)
	} else {
		r0 = ret.Get(0).(model.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.UpdateClientInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClient'
type MockService_UpdateClient_Call struct {
	*mock.Call
}

// UpdateClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - in model.UpdateClientInput
func (_e *MockService_Expecter) UpdateClient(ctx interface{}, id interface{}, in interface{}) *MockService_UpdateClient_Call {
	return &MockService_UpdateClient_Call{Call: _e.mock.On("UpdateClient", ctx, id, in)}
}

func (_c *MockService_UpdateClient_Call) Run(run func(ctx context.Context, id string, in model.UpdateClientInput)) *MockService_UpdateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.UpdateClientInput))
	})
	return _c
}

func (_c *MockService_UpdateClient_Call) Return(_a0 model.Client, _a1 error) *MockService_UpdateClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateClient_Call) RunAndReturn(run func(context.Context, string, model.UpdateClientInput) (model.Client, error)) *MockService_UpdateClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
