// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/all-in-one/internal/oidc/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AuthRequestInfo provides a mock function with given fields: ctx, id
func (_m *MockService) AuthRequestInfo(ctx context.Context, id string) (model.AuthRequestInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthRequestInfo")
	}

	var r0 model.AuthRequestInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.AuthRequestInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.AuthRequestInfo); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.AuthRequestInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_AuthRequestInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthRequestInfo'
type MockService_AuthRequestInfo_Call struct {
	*mock.Call
}

// AuthRequestInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) AuthRequestInfo(ctx interface{}, id interface{}) *MockService_AuthRequestInfo_Call {
	return &MockService_AuthRequestInfo_Call{Call: _e.mock.On("AuthRequestInfo", ctx, id)}
}

func (_c *MockService_AuthRequestInfo_Call) Run(run func(ctx context.Context, id string)) *MockService_AuthRequestInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_AuthRequestInfo_Call) Return(_a0 model.AuthRequestInfo, _a1 error) *MockService_AuthRequestInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_AuthRequestInfo_Call) RunAndReturn(run func(context.Context, string) (model.AuthRequestInfo, error)) *MockService_AuthRequestInfo_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteAuthRequest provides a mock function with given fields: ctx, id, userID
func (_m *MockService) CompleteAuthRequest(ctx context.Context, id string, userID string) (string, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteAuthRequest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CompleteAuthRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteAuthRequest'
type MockService_CompleteAuthRequest_Call struct {
	*mock.Call
}

// CompleteAuthRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockService_Expecter) CompleteAuthRequest(ctx interface{}, id interface{}, userID interface{}) *MockService_CompleteAuthRequest_Call {
	return &MockService_CompleteAuthRequest_Call{Call: _e.mock.On("CompleteAuthRequest", ctx, id, userID)}
}

func (_c *MockService_CompleteAuthRequest_Call) Run(run func(ctx context.Context, id string, userID string)) *MockService_CompleteAuthRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_CompleteAuthRequest_Call) Return(_a0 string, _a1 error) *MockService_CompleteAuthRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CompleteAuthRequest_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockService_CompleteAuthRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
